#### NSR Project Data Wrangling

In [1]:
# import necessary packages
import pandas as pd
import numpy as np
import os

In [2]:
# open csv files as pandas dataframes 

start_y = 2011
max_y = 2024
curr_y = start_y

path = '~/desktop/nsr-project/static/NSRData_CSV/'
data = {}

while curr_y <= max_y: 
    file_name = 'nsr_' + str(curr_y) + '.csv'
    df = pd.read_csv(os.path.join(path,file_name))
    data[curr_y] = df
    curr_y +=1

#### Clean up each dataframe

In [3]:
# Do dataset wide cleanup first?
# def functions to do some basic cleanup
def basic_clean(df):
    df = df.replace('\n',' ', regex=True)
    df = df.replace(['«','»'], ' ',regex=True)
    
    n=0
    for row_index, row in df.iterrows():
        for col_name, cell_val in row.items():
            if df[col_name].dtype == object:
                if not str(cell_val).isascii():
                    n+=1
                    print(col_name,row_index)
    print('New line characters have been removed. Detected', n, 'cell(s) with non-ASCII characters.\nNull Count:\n',df.isnull().sum())
    
    return df

##### Set up column standardization

In [4]:
# 2011

df_2011 = data[2011]
df_2011.head()

   Unnamed: 0    0  ...                     5                      6
0           0  NaN  ...       Port of Loading    Port of Destination
1           1  1.0  ...        Vitino, Russia         Ningbo,\nChina
2           2  2.0  ...        Vitino, Russia  Map Ta Phut, Thailand
3           3  3.0  ...        Vitino, Russia        Huizhou,\nChina
4           4  4.0  ...  Honningsvåg,\nNorway  Map Ta Phut, Thailand

[5 rows x 8 columns]

In [5]:
df_2011.tail()

    Unnamed: 0     0                1  ...        4            5            6
37          37  37.0        Ventspils  ...  ballast         East         West
38          38  38.0  Mikhail Kutuzov  ...  ballast         East         West
39          39  39.0      Ivan Kireev  ...  ballast  Archangelsk    Slavyanka
40          40  40.0          Vengeri  ...  ballast         West         East
41          41  41.0      Mar Adriana  ...  ballast    Rotterdam  Vladivostok

[5 rows x 8 columns]

In [6]:
df_2011.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 42 entries, 0 to 41
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  42 non-null     int64
 1   0           41 non-null     float64
 2   1           42 non-null     object
 3   2           42 non-null     object
 4   3           42 non-null     object
 5   4           42 non-null     object
 6   5           42 non-null     object
 7   6           42 non-null     object
dtypes: float64(1), int64(1), object(6)
memory usage: 2.8+ KB

In [7]:
# make row index 0 into column headers
df_2011.columns = df_2011.iloc[0]
df_2011 = df_2011[1:]
df_2011.reset_index(drop=True, inplace=True)
df_2011.rename(columns=str)

df_2011.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 41 entries, 0 to 40
Data columns (total 8 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   0                    41 non-null     int64
 1   nan                  41 non-null     float64
 2   Vessel’s Name        41 non-null     object
 3   Type                 41 non-null     object
 4   Flag                 41 non-null     object
 5   Cargo                41 non-null     object
 6   Port of Loading      41 non-null     object
 7   Port of Destination  41 non-null     object
dtypes: float64(1), int64(1), object(6)
memory usage: 2.7+ KB

In [8]:
# change column header names
df_2011.columns = ['index','index2','vessel name','type','flag','cargo','port of loading','port of destination']
df_2011.columns

Index(['index', 'index2', 'vessel name', 'type', 'flag', 'cargo',
       'port of loading', 'port of destination'],
      dtype='object')

In [9]:
df_2011 = df_2011.drop(['index','index2'],axis=1)

In [10]:
df_2011.head()

         vessel name  ...    port of destination
0       Perseverance  ...         Ningbo,\nChina
1       STI Heritage  ...  Map Ta Phut, Thailand
2            Marilee  ...        Huizhou,\nChina
3  Vladimir Tikhonov  ...  Map Ta Phut, Thailand
4     Stena Poseidon  ...  Incheon,\nSouth Korea

[5 rows x 6 columns]

In [11]:
df_2011 = basic_clean(df_2011)

port of loading 3
vessel name 29
New line characters have been removed. Detected 2 cell(s) with non-ASCII characters.
Null Count:
 vessel name            0
type                   0
flag                   0
cargo                  0
port of loading        0
port of destination    0
dtype: int64

In [12]:
df_2011.head()

         vessel name           type  ...      port of loading    port of destination
0       Perseverance  Tanker vessel  ...       Vitino, Russia          Ningbo, China
1       STI Heritage  Tanker vessel  ...       Vitino, Russia  Map Ta Phut, Thailand
2            Marilee  Tanker vessel  ...       Vitino, Russia         Huizhou, China
3  Vladimir Tikhonov  Tanker vessel  ...  Honningsvåg, Norway  Map Ta Phut, Thailand
4     Stena Poseidon  Tanker vessel  ...       Vitino, Russia   Incheon, South Korea

[5 rows x 6 columns]

In [13]:
# 2012
df_2012 = data[2012]

df_2012.head()

   Unnamed: 0  0  ...                     10   11
0           0  №  ...  Average speed,\nknots  NaN
1           1  1  ...                   5,8.  NaN
2           2  2  ...                    5,9  NaN
3           3  3  ...                    7,3  NaN
4           4  4  ...                    9,7  NaN

[5 rows x 13 columns]

In [14]:
df_2012.tail(10)

    Unnamed: 0  ...                             11
52          52  ...                            NaN
53          53  ...                            NaN
54          54  ...  Full\nDisplacement\nWestbound
55          55  ...                            NaN
56          56  ...                            NaN
57          57  ...                            NaN
58          58  ...                            NaN
59          59  ...                        472 075
60          60  ...                         63 986
61          61  ...                        536 061

[10 rows x 13 columns]

In [15]:
df_2012_totals = df_2012[54:62]
df_2012_totals.head(10)

    Unnamed: 0  ...                             11
54          54  ...  Full\nDisplacement\nWestbound
55          55  ...                            NaN
56          56  ...                            NaN
57          57  ...                            NaN
58          58  ...                            NaN
59          59  ...                        472 075
60          60  ...                         63 986
61          61  ...                        536 061

[8 rows x 13 columns]

In [16]:
df_2012 = df_2012[0:54]
df_2012.tail()

    Unnamed: 0   0                                 1  ...     9    10   11
49          49  42     Mv\n«Nordic\nOdyssey»\nPANAMA  ...  10.0  10.4  NaN
50          50  43       mv\n«Nordic\nOrion»\nPANAMA  ...  10.5  10,3  NaN
51          51  44  LNG\n«Ob River»\nMarshall Island  ...   9.0  12,5  NaN
52          52  45    icebreaker\n«Nordica»\nFINLAND  ...   NaN   NaN  NaN
53          53  46    icebreaker\n«Fennica»\nFINLAND  ...   NaN   NaN  NaN

[5 rows x 13 columns]

In [17]:
df_2012.head()

   Unnamed: 0  0  ...                     10   11
0           0  №  ...  Average speed,\nknots  NaN
1           1  1  ...                   5,8.  NaN
2           2  2  ...                    5,9  NaN
3           3  3  ...                    7,3  NaN
4           4  4  ...                    9,7  NaN

[5 rows x 13 columns]

In [18]:
# change column header names
# need to mold data into df.columns = ['index','index2','vessel name','type','flag','cargo','port of loading','port of destination']
df_2012.columns = ['index','index2', 'vessel and flag','ice class','ship operator','cargo','port of destination','port and date','entry to nsr','exit from nsr','time elapsed on nsr','avg speed','index3']
df_2012.columns

Index(['index', 'index2', 'vessel and flag', 'ice class', 'ship operator',
       'cargo', 'port of destination', 'port and date', 'entry to nsr',
       'exit from nsr', 'time elapsed on nsr', 'avg speed', 'index3'],
      dtype='object')

In [19]:
df_2012 = df_2012.drop(['index','index2','index3'],axis=1)
df_2012.columns

Index(['vessel and flag', 'ice class', 'ship operator', 'cargo',
       'port of destination', 'port and date', 'entry to nsr', 'exit from nsr',
       'time elapsed on nsr', 'avg speed'],
      dtype='object')

In [20]:
df_2012 = basic_clean(df_2012)
df_2012.head()

cargo 4
port of destination 4
port of destination 5
avg speed 8
avg speed 9
avg speed 13
cargo 30
port of destination 38
vessel and flag 41
entry to nsr 45
exit from nsr 45
ship operator 46
vessel and flag 48
port of destination 50
cargo 51
New line characters have been removed. Detected 15 cell(s) with non-ASCII characters.
Null Count:
 vessel and flag        0
ice class              2
ship operator          3
cargo                  1
port of destination    2
port and date          1
entry to nsr           2
exit from nsr          4
time elapsed on nsr    5
avg speed              5
dtype: int64

                  vessel and flag  ...             avg speed
0                 Vessel and Flag  ...  Average speed, knots
1             mt  Varzuga  Russia  ...                  5,8.
2              Mt  Indiga  Russia  ...                   5,9
3  Supply vessel  Vengeri  Russia  ...                   7,3
4      mt  Nordic Odyssey  PANAMA  ...                   9,7

[5 rows x 10 columns]

In [21]:
df_2012 = df_2012[1:]
df_2012.reset_index(inplace=True)
df_2012 = df_2012.drop('index',axis=1)
df_2012.head()

                  vessel and flag  ... avg speed
0             mt  Varzuga  Russia  ...      5,8.
1              Mt  Indiga  Russia  ...       5,9
2  Supply vessel  Vengeri  Russia  ...       7,3
3      mt  Nordic Odyssey  PANAMA  ...       9,7
4             mt  Marilee  NORWAY  ...       9,6

[5 rows x 10 columns]

In [22]:
# split some columns to sequester info nicer
# splitting vessel and flag --> vessel, flag
# splitting port and date --> starting port, trip start date
df_2012[['vessel', 'flag']] = df_2012['vessel and flag'].str.rsplit(n=1, expand=True)
df_2012.drop('vessel and flag',axis=1,inplace=True)

df_2012[['starting port','starting date']] = df_2012['port and date'].str.split(n=1,expand=True)
df_2012.drop('port and date',axis=1, inplace=True)

# df_2012[['cargo weight','cargo type']] = df_2012['cargo'].str.split('',n=1,regex=True)
# df_2012.drop('cargo',axis=1,inplace=True)

df_2012[['starting date','starting time']] = df_2012['starting date'].str.split(n=1,expand=True)

df_2012[['nsr entry date','nsr entry time']] = df_2012['entry to nsr'].str.split(n=1,expand=True)
df_2012.drop('entry to nsr',axis=1,inplace=True)

df_2012[['nsr exit date','nsr exit time']] = df_2012['exit from nsr'].str.split(n=1,expand=True)
df_2012.drop('exit from nsr',axis=1,inplace=True)

# need to get solve problem of time stamps 
df_2012.head()

              ice class         ship operator  ... nsr exit date nsr exit time
0                  Arc5              JSC MSCo  ...      16.07.12         10:00
1                  Arc5              JSC MSCo  ...      16.07.12         10:00
2  Ice 1A Super (Arc 5)             FEMCO LTD  ...      23.07.12         00:00
3         Ice 1A (Arc4)  Nordic Bulk Carriers  ...      23.07.12         05:00
4         Ice 1A (Arc4)             MARINVEST  ...      22.07.12         23:40

[5 rows x 15 columns]

In [23]:
# standardize cell structure and ensure ASCII characters
df_2012.loc[0,'time elapsed on nsr'] = 19.5
df_2012.loc[1,'time elapsed on nsr'] = 17.4

df_2012.head()

              ice class         ship operator  ... nsr exit date nsr exit time
0                  Arc5              JSC MSCo  ...      16.07.12         10:00
1                  Arc5              JSC MSCo  ...      16.07.12         10:00
2  Ice 1A Super (Arc 5)             FEMCO LTD  ...      23.07.12         00:00
3         Ice 1A (Arc4)  Nordic Bulk Carriers  ...      23.07.12         05:00
4         Ice 1A (Arc4)             MARINVEST  ...      22.07.12         23:40

[5 rows x 15 columns]

In [24]:
# 2013

df_2013 = data[2013]
df_2013.head()

   Unnamed: 0    0                                    1  ...   12   13   14
0           0  No.                      Vessel and Flag  ...  NaN  NaN  NaN
1           1    1           mt\n«Varzuga»\nflag RUSSIA  ...  NaN  NaN  NaN
2           2    2            mt\n«Indiga»\nflag RUSSIA  ...  NaN  NaN  NaN
3           3    3      mv\n«Nordic Orion»\nflag PANAMA  ...  NaN  NaN  NaN
4           4    4  mv\n«Boris Vilkitskiy»\nflag RUSSIA  ...  NaN  NaN  NaN

[5 rows x 16 columns]

In [25]:
df_2013.tail(10)

    Unnamed: 0               0  ...                  13                  14
75          75              67  ...                 NaN                 NaN
76          76              68  ...                 NaN                 NaN
77          77  Type of\ncargo  ...  Empty\nvessels\nWB  WB\ndispl.,\ntones
78          78          Liquid  ...                 NaN                 NaN
79          79            Bulk  ...                 NaN                 NaN
80          80             LNG  ...                 NaN                 NaN
81          81   General cargo  ...                 NaN                 NaN
82          82      Ballasting  ...                  14             467 445
83          83      Reposition  ...                   3              29 388
84          84          TOTAL:  ...                  17             496 833

[10 rows x 16 columns]

In [26]:
df_2013_totals = df_2013[77:85]
df_2013_totals.head(10)

    Unnamed: 0               0  ...                  13                  14
77          77  Type of\ncargo  ...  Empty\nvessels\nWB  WB\ndispl.,\ntones
78          78          Liquid  ...                 NaN                 NaN
79          79            Bulk  ...                 NaN                 NaN
80          80             LNG  ...                 NaN                 NaN
81          81   General cargo  ...                 NaN                 NaN
82          82      Ballasting  ...                  14             467 445
83          83      Reposition  ...                   3              29 388
84          84          TOTAL:  ...                  17             496 833

[8 rows x 16 columns]

In [27]:
df_2013 = df_2013[:77]
df_2013.tail()

    Unnamed: 0   0                                          1  ...   12   13   14
72          72  64          mv «HHL Hong\nKong»\nflag LIBERIA  ...  NaN  NaN  NaN
73          73  65        icebreaker\n«Fennica»\nflag FINLAND  ...  NaN  NaN  NaN
74          74  66                  mt\n«Indiga»\nflag RUSSIA  ...  NaN  NaN  NaN
75          75  67  mv «HHL Lagos»\nflag Antigua and\nBarbuda  ...  NaN  NaN  NaN
76          76  68                     mv «Yuri\nArshenevsky»  ...  NaN  NaN  NaN

[5 rows x 16 columns]

In [28]:
df_2013.columns = ['index','index2','vessel and flag','ice class','grt (tons)','vessel operator','cargo','port of destination','port and date of departure','entry to nsr','exit from nsr','time elapsed on nsr','avg speed (knots)','index3','index4','index5']
df_2013.head()

   index index2                      vessel and flag  ... index3 index4 index5
0      0    No.                      Vessel and Flag  ...    NaN    NaN    NaN
1      1      1           mt\n«Varzuga»\nflag RUSSIA  ...    NaN    NaN    NaN
2      2      2            mt\n«Indiga»\nflag RUSSIA  ...    NaN    NaN    NaN
3      3      3      mv\n«Nordic Orion»\nflag PANAMA  ...    NaN    NaN    NaN
4      4      4  mv\n«Boris Vilkitskiy»\nflag RUSSIA  ...    NaN    NaN    NaN

[5 rows x 16 columns]

In [29]:
df_2013 = df_2013.drop(['index','index2','index3','index4','index5'],axis=1)
df_2013 = df_2013.drop([0],axis=0)
df_2013.head()

                       vessel and flag  ... avg speed (knots)
1           mt\n«Varzuga»\nflag RUSSIA  ...               7,0
2            mt\n«Indiga»\nflag RUSSIA  ...               9,2
3      mv\n«Nordic Orion»\nflag PANAMA  ...               5,4
4  mv\n«Boris Vilkitskiy»\nflag RUSSIA  ...               4,3
5            mt\n«Indiga»\nflag RUSSIA  ...               7,2

[5 rows x 11 columns]

In [30]:
df_2013 = basic_clean(df_2013)

port of destination 1
vessel and flag 10
cargo 34
port and date of departure 75
New line characters have been removed. Detected 4 cell(s) with non-ASCII characters.
Null Count:
 vessel and flag               1
ice class                     2
grt (tons)                    3
vessel operator               2
cargo                         1
port of destination           1
port and date of departure    1
entry to nsr                  1
exit from nsr                 1
time elapsed on nsr           3
avg speed (knots)             3
dtype: int64

In [31]:
df_2013.head()

                     vessel and flag  ... avg speed (knots)
1           mt  Varzuga  flag RUSSIA  ...               7,0
2            mt  Indiga  flag RUSSIA  ...               9,2
3      mv  Nordic Orion  flag PANAMA  ...               5,4
4  mv  Boris Vilkitskiy  flag RUSSIA  ...               4,3
5            mt  Indiga  flag RUSSIA  ...               7,2

[5 rows x 11 columns]

In [32]:
# split columns into standardized column format

df_2013[['vessel','flag']] = df_2013['vessel and flag'].str.split('flag',n=1,expand=True)
df_2013.drop('vessel and flag', axis=1,inplace=True)

df_2013[['starting port','starting date','starting time']] = df_2013['port and date of departure'].str.split(n=2,expand=True)
df_2013.drop('port and date of departure',axis=1,inplace=True)

df_2013[['entry date','entry time','nsr entry location']] = df_2013['entry to nsr'].str.split(n=2,expand=True)
df_2013.drop('entry to nsr',axis=1,inplace=True)

df_2013[['exit date','exit time','nsr exit location']] = df_2013['exit from nsr'].str.split(n=2,expand=True)
df_2013.drop('exit from nsr',axis=1,inplace=True)

df_2013.head()

       ice class grt (tons)  ... exit time nsr exit location
1           Arc5     11 290  ...     14:00        c. Dezhnev
2           Arc5     11 290  ...     09:20             Pevek
3  Ice-1A (Arc4)     40 142  ...     08:55        c. Dezhnev
4           Arc4      5 025  ...     24:00      Khatanga Bay
5           Arc5     11 290  ...     12:50            Ob Bay

[5 rows x 18 columns]

In [33]:
# 2014

df_2014 = data[2014]
df_2014.head()

   Unnamed: 0  ...                   9
0           0  ...  Days spent\nat NSR
1           1  ...                 NaN
2           2  ...                  30
3           3  ...                  13
4           4  ...                  43

[5 rows x 11 columns]

In [34]:
df_2014.tail()

    Unnamed: 0   0            1  ...            7         8   9
51          51  18      Varzuga  ...   port Pevek  28.10.14  11
52          52  19       Indiga  ...  c. Zhelania  17.11.14  28
53          53  20      Varzuga  ...  c. Zhelania  17.11.14  17
54          54  21       Indiga  ...  c. Zhelania  17.11.14  13
55          55  22  Ivan Ryabov  ...  c. Zhelania  16.11.14  10

[5 rows x 11 columns]

In [35]:
# rename columns to get closer to standardization

df_2014.columns = ['index','index2','vessel','flag','cargo','GRT','nsr entry date','nsr entry location','nsr exit location','nsr exit date','time elapsed on nsr']
df_2014.head()

   index  ... time elapsed on nsr
0      0  ...  Days spent\nat NSR
1      1  ...                 NaN
2      2  ...                  30
3      3  ...                  13
4      4  ...                  43

[5 rows x 11 columns]

In [36]:
# drop irrelevant columns and rows
df_2014.drop('index',axis=1,inplace=True)
df_2014.drop('index2',axis=1,inplace=True)
df_2014.drop(0,axis=0,inplace=True)
df_2014.drop(1,axis=0,inplace=True)

df_2014.reset_index(drop=True,inplace=True)

df_2014.head()

               vessel    flag  ... nsr exit date time elapsed on nsr
0  Kapitan Khlebnikov  Russia  ...      28.07.14                  30
1          Tor Viking  Sweden  ...      16.07.14                  13
2     Anichkov Bridge  Russia  ...      17.08.14                  43
3                Oden  Sweden  ...      17.08.14                  39
4     Yaroslav Mydryy  Russia  ...      28.07.14                  19

[5 rows x 9 columns]

In [37]:
df_2014 = basic_clean(df_2014)

New line characters have been removed. Detected 0 cell(s) with non-ASCII characters.
Null Count:
 vessel                 1
flag                   1
cargo                  1
GRT                    1
nsr entry date         1
nsr entry location     1
nsr exit location      1
nsr exit date          1
time elapsed on nsr    1
dtype: int64

In [38]:
# 2015

df_2015 = data[2015]
df_2015.head()

   Unnamed: 0  0  ...                     14                         15
0           0  №  ...  EBNSR\n(Cape Dezhnev)  NSR\npassage\ntime (days)
1           1  1  ...         15.08.15 23:30                       16,9
2           2  2  ...          02.08.15 3:30                        8,5
3           3  3  ...          16.08.15 8:23                        9,7
4           4  4  ...         14.08.15 12:23                       10,3

[5 rows x 17 columns]

In [39]:
df_2015.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 17 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  20 non-null     int64
 1   0           20 non-null     object
 2   1           19 non-null     object
 3   2           19 non-null     object
 4   3           19 non-null     object
 5   4           19 non-null     object
 6   5           19 non-null     object
 7   6           13 non-null     object
 8   7           20 non-null     object
 9   8           20 non-null     object
 10  9           19 non-null     object
 11  10          19 non-null     object
 12  11          19 non-null     object
 13  12          13 non-null     object
 14  13          7 non-null      object
 15  14          19 non-null     object
 16  15          20 non-null     object
dtypes: int64(1), object(16)
memory usage: 2.8+ KB

In [40]:
df_2015.tail()

    Unnamed: 0      0             1  ...              13             14    15
15          15     15  Volk Arktiki  ...             NaN  14.10.15 2:30  14,3
16          16     16      Palladiy  ...             NaN  25.10.15 2:00  16,3
17          17     17      Kigoriak  ...             NaN  08.11.15 6:20  13,9
18          18     18    Tor Viking  ...  10.12.15 12:00  29.11.15 7:10  11,2
19          19  Total           NaN  ...             NaN            NaN  10,6

[5 rows x 17 columns]

In [41]:
# rename columns to closer adhere to standardization

df_2015.columns = ['index','index2','vessel','flag','ship operator','ice class','ship type','cargo type','cargo weight','max draught','port of departure','port of destination','icebreaker assistance','Kara Gate date and time','Cape Zhelaniya date and time','Cape Dezhnev date and time','time elapsed on nsr']
df_2015.head()

   index index2  ... Cape Dezhnev date and time        time elapsed on nsr
0      0      №  ...      EBNSR\n(Cape Dezhnev)  NSR\npassage\ntime (days)
1      1      1  ...             15.08.15 23:30                       16,9
2      2      2  ...              02.08.15 3:30                        8,5
3      3      3  ...              16.08.15 8:23                        9,7
4      4      4  ...             14.08.15 12:23                       10,3

[5 rows x 17 columns]

In [42]:
# drop irrelevant columns and rows

df_2015.drop(19,axis=0,inplace=True)
df_2015.drop(0,axis=0,inplace=True)
df_2015.drop('index',axis=1,inplace=True)
df_2015.drop('index2',axis=1,inplace=True)

df_2015.head()

                                      vessel  ... time elapsed on nsr
1  Yasnyi (with\nfloating crane СПК-\n42150)  ...                16,9
2                                 Yong Sheng  ...                 8,5
3                                 Winter Bay  ...                 9,7
4                                   Garmonia  ...                10,3
5                                  Happy Sky  ...                 7,7

[5 rows x 15 columns]

In [43]:
df_2015 = basic_clean(df_2015)

vessel 1
vessel 8
New line characters have been removed. Detected 2 cell(s) with non-ASCII characters.
Null Count:
 vessel                           0
flag                             0
ship operator                    0
ice class                        0
ship type                        0
cargo type                       6
cargo weight                     0
max draught                      0
port of departure                0
port of destination              0
icebreaker assistance            0
Kara Gate date and time          6
Cape Zhelaniya date and time    12
Cape Dezhnev date and time       0
time elapsed on nsr              0
dtype: int64

In [44]:
df_2015.head()

                                    vessel  ... time elapsed on nsr
1  Yasnyi (with floating crane СПК- 42150)  ...                16,9
2                               Yong Sheng  ...                 8,5
3                               Winter Bay  ...                 9,7
4                                 Garmonia  ...                10,3
5                                Happy Sky  ...                 7,7

[5 rows x 15 columns]

In [45]:
# expand checkpoint fields separating date and time

df_2015[['Kara Gate date','Kara Gate time']] = df_2015['Kara Gate date and time'].str.split(n=1,expand=True)
df_2015.drop('Kara Gate date and time',axis=1,inplace=True)

df_2015[['Cape Zhelaniya date','Cape Zhelaniya time']] = df_2015['Cape Zhelaniya date and time'].str.split(n=1,expand=True)
df_2015.drop('Cape Zhelaniya date and time',axis=1,inplace=True)

df_2015[['Cape Dezhnev date','Cape Deshnev time']] = df_2015['Cape Dezhnev date and time'].str.split(n=1,expand=True)
df_2015.drop('Cape Dezhnev date and time',axis=1,inplace=True)

In [46]:
df_2015.head()

                                    vessel  ... Cape Deshnev time
1  Yasnyi (with floating crane СПК- 42150)  ...             23:30
2                               Yong Sheng  ...              3:30
3                               Winter Bay  ...              8:23
4                                 Garmonia  ...             12:23
5                                Happy Sky  ...              7:25

[5 rows x 18 columns]

In [47]:
df_2015.tail()

          vessel    flag  ... Cape Dezhnev date Cape Deshnev time
14        Yasnyi  Russia  ...          11.10.15              0:05
15  Volk Arktiki  Russia  ...          14.10.15              2:30
16      Palladiy  Russia  ...          25.10.15              2:00
17      Kigoriak  Russia  ...          08.11.15              6:20
18    Tor Viking  Sweden  ...          29.11.15              7:10

[5 rows x 18 columns]

In [48]:
# 2016

df_2016 = data[2016]

df_2016.head()

   Unnamed: 0   0  ...                     17                          18
0           0 NaN  ...  EBNSR\n(Cape Dezhnev)  NSR\npassage\ntime\n(days)
1           1 NaN  ...          16.07.16 2:30                        11,8
2           2 NaN  ...         21.07.16 18:30                        15,5
3           3 NaN  ...          28.07.16 7:00                         9,3
4           4 NaN  ...          20.08.16 9:50                        21,1

[5 rows x 20 columns]

In [49]:
df_2016.tail()

    Unnamed: 0   0      1  ...              16              17    18
16          16 NaN     17  ...  02.11.16 12:00  17.11.16 17:45  15,2
17          17 NaN     18  ...  03.11.16 20:30  11.11.16 19:06   7,9
18          18 NaN     19  ...   08.11.16 8:10  17.11.16 18:20   9,4
19          19 NaN  Total  ...             NaN             NaN  14,3
20          20 NaN    NaN  ...             NaN             NaN   NaN

[5 rows x 20 columns]

In [50]:
# standardize column names

df_2016.columns = ['index','index2','index3','vessel name','flag','ship operator','ice class','ship type','cargo type','cargo weight','dead weight tonnage','max draught','port of departure','port of destination','icebreaker assistance','Kara Gate date and time','Yugorskiy Strait date and time','Cape Zhelaniya date and time','Cape Dezhnev date and time','time elapsed on nsr']

df_2016.head()

   index  index2  ... Cape Dezhnev date and time         time elapsed on nsr
0      0     NaN  ...      EBNSR\n(Cape Dezhnev)  NSR\npassage\ntime\n(days)
1      1     NaN  ...              16.07.16 2:30                        11,8
2      2     NaN  ...             21.07.16 18:30                        15,5
3      3     NaN  ...              28.07.16 7:00                         9,3
4      4     NaN  ...              20.08.16 9:50                        21,1

[5 rows x 20 columns]

In [51]:
# drop unnecessary columns

df_2016.drop(['index','index2','index3'],axis=1,inplace=True)
df_2016.drop([0,19,20],axis=0,inplace=True)

df_2016.tail()

        vessel name  ... time elapsed on nsr
14       Winter Bay  ...                 8,4
15  Inzhener Trubin  ...                11,7
16          Normann  ...                15,2
17   HHL Valparaiso  ...                 7,9
18            Pomor  ...                 9,4

[5 rows x 17 columns]

In [52]:
df_2016 = basic_clean(df_2016)

ship operator 4
New line characters have been removed. Detected 1 cell(s) with non-ASCII characters.
Null Count:
 vessel name                        0
flag                               0
ship operator                      0
ice class                          0
ship type                          0
cargo type                         6
cargo weight                       0
dead weight tonnage                0
max draught                        1
port of departure                  0
port of destination                0
icebreaker assistance              3
Kara Gate date and time           15
Yugorskiy Strait date and time    17
Cape Zhelaniya date and time       4
Cape Dezhnev date and time         0
time elapsed on nsr                0
dtype: int64

In [53]:
df_2016.head()

          vessel name       flag  ... Cape Dezhnev date and time time elapsed on nsr
1  Kapitan Khlebnikov     Russia  ...              16.07.16 2:30                11,8
2        Brage Viking     Russia  ...             21.07.16 18:30                15,5
3          Yong Sheng  Hong Kong  ...              28.07.16 7:00                 9,3
4      Spasatel Karev     Russia  ...              20.08.16 9:50                21,1
5    Gretke Oldendorf   Portugal  ...              03.08.16 6:00                25,7

[5 rows x 17 columns]

In [54]:
# expand columns 

df_2016[['Kara Gate date','Kara Gate time']] = df_2016['Kara Gate date and time'].str.split(n=1,expand=True)

df_2016[['Yugorskiy Strait date','Yugorskiy Strait time']] = df_2016['Yugorskiy Strait date and time'].str.split(n=1,expand=True)

df_2016[['Cape Zhelaniya date','Cape Zhelaniya time']] = df_2016['Cape Zhelaniya date and time'].str.split(n=1,expand=True)

df_2016[['Cape Dezhnev date','Cape Dezhnev time']] = df_2016['Cape Dezhnev date and time'].str.split(n=1,expand=True)

df_2016.drop(['Kara Gate date and time','Yugorskiy Strait date and time','Cape Zhelaniya date and time','Cape Dezhnev date and time'],axis=1,inplace=True)

In [55]:
df_2016.head()

          vessel name       flag  ... Cape Dezhnev date Cape Dezhnev time
1  Kapitan Khlebnikov     Russia  ...          16.07.16              2:30
2        Brage Viking     Russia  ...          21.07.16             18:30
3          Yong Sheng  Hong Kong  ...          28.07.16              7:00
4      Spasatel Karev     Russia  ...          20.08.16              9:50
5    Gretke Oldendorf   Portugal  ...          03.08.16              6:00

[5 rows x 21 columns]

In [56]:
# 2017

df_2017 = data[2017]

df_2017.head()

   Unnamed: 0  0  ...          17                        18
0           0  N  ...  Entry date  NSR passage\ntime (days)
1           1  1  ...    24.09.17                       6,6
2           2  2  ...    14.09.17                       6,1
3           3  3  ...    04.09.17                       7,9
4           4  4  ...    07.10.17                       7,8

[5 rows x 20 columns]

In [57]:
df_2017.tail()

    Unnamed: 0   0               1  ...           16        17    18
23          23  23       Egvekinot  ...  Provideniya  29.08.17  10,9
24          24  24        HHL Elbe  ...      Kholmsk  05.08.17  10,4
25          25  25         Siziman  ...      Lanshan  09.10.17  12,9
26          26  26  Rolldock Storm  ...      Qingdao  08.10.17   7,4
27          27  27       Garmoniya  ...  Arkhangelsk  23.08.17  10,0

[5 rows x 20 columns]

In [58]:
df_2017.columns = ['index','index2','vessel name','dead weight tonnage','grt','flag','ship operator','ship type','imo ship id','length overall','ice class','port of departure','departure date and time','nsr entrance point','nsr entry date','nsr exit point','nsr exit date','port of destination','arrival date','time elapsed on nsr']

df_2017.head()

   index index2  ... arrival date       time elapsed on nsr
0      0      N  ...   Entry date  NSR passage\ntime (days)
1      1      1  ...     24.09.17                       6,6
2      2      2  ...     14.09.17                       6,1
3      3      3  ...     04.09.17                       7,9
4      4      4  ...     07.10.17                       7,8

[5 rows x 20 columns]

In [59]:
# drop unnecessary columns

df_2017.drop(['index','index2'],axis=1,inplace=True)

df_2017.drop(0,axis=0,inplace=True)

df_2017.head()

  vessel name dead weight tonnage  ... arrival date time elapsed on nsr
1   Tian Jian               38146  ...     24.09.17                 6,6
2       Da An               28000  ...     14.09.17                 6,1
3   Foresight               12669  ...     04.09.17                 7,9
4     Fortune               12692  ...     07.10.17                 7,8
5     Finesse               12685  ...     21.10.17                 6,9

[5 rows x 18 columns]

In [60]:
df_2017 = basic_clean(df_2017)

New line characters have been removed. Detected 0 cell(s) with non-ASCII characters.
Null Count:
 vessel name                0
dead weight tonnage        0
grt                        0
flag                       0
ship operator              0
ship type                  0
imo ship id                0
length overall             0
ice class                  0
port of departure          0
departure date and time    0
nsr entrance point         0
nsr entry date             0
nsr exit point             0
nsr exit date              0
port of destination        0
arrival date               0
time elapsed on nsr        0
dtype: int64

In [61]:
# expand columns
df_2017[['departure date','departure time']] = df_2017['departure date and time'].str.split(n=1,expand=True)
df_2017.drop('departure date and time',axis=1,inplace=True)

In [62]:
df_2017.tail()

       vessel name dead weight tonnage  ... departure date departure time
23       Egvekinot                6026  ...     13.08.2017          22:40
24        HHL Elbe               12709  ...     14.07.2017           3:00
25         Siziman                4800  ...     04.09.2017          23:00
26  Rolldock Storm                9063  ...     18.09.2017           9:00
27       Garmoniya                3642  ...     07.08.2017           1:30

[5 rows x 19 columns]

In [63]:
# 2018

df_2018 = data[2018]
df_2018.head()

   Unnamed: 0    0            1  ...       14         15        16
0           0  NaN       Vessel  ...  Arrival        NaN       NaN
1           1  NaN  Vessel name  ...  Country       Port      Date
2           2  1.0     Tian Hui  ...    Japan  Tomakomai  12.08.18
3           3  2.0     Tian You  ...   Sweden  Harnosand  20.08.18
4           4  3.0    Tian Jian  ...    China    Qingdao  02.09.18

[5 rows x 18 columns]

In [64]:
df_2018.tail()

    Unnamed: 0     0             1  ...      14           15        16
24          24  23.0      Tian Hui  ...  Sweden   Oskarshamn  15.10.18
25          25  24.0     Egvekinot  ...  Russia  Provideniya  20.09.18
26          26  25.0      Tian You  ...   China       Nansha  25.10.18
27          27  26.0          Argo  ...  Russia  Arkhangelsk  19.10.18
28          28  27.0  Novorossiysk  ...  Russia       Vanino  17.12.18

[5 rows x 18 columns]

In [65]:
df_2018.columns = ['index','index2','vessel name','ice class','flag','ship operator','ship type','grt','departure country','departure port','departure date','nsr entry point','nsr entry date','nsr exit point','nsr exit date','arrival country','arrival port','arrival date']
df_2018.head()

   index  index2  vessel name  ... arrival country arrival port arrival date
0      0     NaN       Vessel  ...         Arrival          NaN          NaN
1      1     NaN  Vessel name  ...         Country         Port         Date
2      2     1.0     Tian Hui  ...           Japan    Tomakomai     12.08.18
3      3     2.0     Tian You  ...          Sweden    Harnosand     20.08.18
4      4     3.0    Tian Jian  ...           China      Qingdao     02.09.18

[5 rows x 18 columns]

In [66]:
df_2018.drop(['index','index2'],axis=1,inplace=True)
df_2018.drop([0,1],axis=0,inplace=True)
df_2018.reset_index(drop=True,inplace=True)
df_2018.head()

       vessel name ice class  ... arrival port arrival date
0         Tian Hui     Arc 4  ...    Tomakomai     12.08.18
1         Tian You     Arc 4  ...    Harnosand     20.08.18
2        Tian Jian     Ice 1  ...      Qingdao     02.09.18
3  Atlantic Winter     Arc 4  ...    Harnosand     31.08.18
4           Kairos        No  ...     Murmansk     29.08.18

[5 rows x 16 columns]

In [67]:
df_2018 = basic_clean(df_2018)
df_2018.head()

New line characters have been removed. Detected 0 cell(s) with non-ASCII characters.
Null Count:
 vessel name          0
ice class            0
flag                 0
ship operator        0
ship type            0
grt                  0
departure country    0
departure port       0
departure date       0
nsr entry point      0
nsr entry date       0
nsr exit point       0
nsr exit date        0
arrival country      0
arrival port         0
arrival date         0
dtype: int64

       vessel name ice class  ... arrival port arrival date
0         Tian Hui     Arc 4  ...    Tomakomai     12.08.18
1         Tian You     Arc 4  ...    Harnosand     20.08.18
2        Tian Jian     Ice 1  ...      Qingdao     02.09.18
3  Atlantic Winter     Arc 4  ...    Harnosand     31.08.18
4           Kairos        No  ...     Murmansk     29.08.18

[5 rows x 16 columns]

In [68]:
# 2019

df_2019 = data[2019]
df_2019.head()

              Vessel name      IMO  ...     Arr Port    Arr Date
0                 Tian En  9774587  ...        Gavle  2019-08-17
1            Svyatoy Petr  9035838  ...  Arkhangelsk  2019-08-10
2  Professor Multanovskiy  8010362  ...     Murmansk  2019-09-07
3                  Da Tai  9608386  ...       Skagen  2019-08-24
4               Simfoniya  8516627  ...  Arkhangelsk  2019-08-19

[5 rows x 15 columns]

In [69]:
df_2019.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 36 entries, 0 to 35
Data columns (total 15 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Vessel name       36 non-null     object
 1   IMO               36 non-null     int64
 2   Ice class         36 non-null     object
 3   Flag              36 non-null     object
 4   Owner / Operator  36 non-null     object
 5   Vessel type       36 non-null     object
 6   DWT               36 non-null     int64
 7   GRT               36 non-null     int64
 8   LOA               36 non-null     float64
 9   Dep Country       36 non-null     object
 10  Dep Port          36 non-null     object
 11  Dep Date          36 non-null     object
 12  Arr Country       36 non-null     object
 13  Arr Port          36 non-null     object
 14  Arr Date          36 non-null     object
dtypes: float64(1), int64(3), object(11)
memory usage: 4.3+ KB

In [70]:
df_2019.columns = ['vessel name','imo ship id','ice class','flag','ship operator','ship type','dead weight tonnage','grt','length overall','country of departure','port of departure','date of departure','country of arrival','port of arrival','date of arrival']

In [71]:
df_2019.head()

              vessel name  imo ship id  ... port of arrival date of arrival
0                 Tian En      9774587  ...           Gavle      2019-08-17
1            Svyatoy Petr      9035838  ...     Arkhangelsk      2019-08-10
2  Professor Multanovskiy      8010362  ...        Murmansk      2019-09-07
3                  Da Tai      9608386  ...          Skagen      2019-08-24
4               Simfoniya      8516627  ...     Arkhangelsk      2019-08-19

[5 rows x 15 columns]

In [72]:
df_2019 = basic_clean(df_2019)

New line characters have been removed. Detected 0 cell(s) with non-ASCII characters.
Null Count:
 vessel name             0
imo ship id             0
ice class               0
flag                    0
ship operator           0
ship type               0
dead weight tonnage     0
grt                     0
length overall          0
country of departure    0
port of departure       0
date of departure       0
country of arrival      0
port of arrival         0
date of arrival         0
dtype: int64

In [73]:
# 2020

df_2020 = data[2020]

df_2020.head()

       Vessel name      IMO  ...                   Arr Port    Arr Date
0          Barents  9278600  ...              Bolshoy Kamen  2020-08-07
1      S,Kuznetsov  9210359  ...  Petropavlovsk-Kamchatskiy  2020-08-06
2  Nordic Svalbard  9437323  ...                Vladivostok  2020-08-12
3          Tian En  9774587  ...                      Emden  2020-08-19
4           Samson  9114751  ...                 Bering Sea  2020-08-07

[5 rows x 15 columns]

In [74]:
df_2020.tail()

                  Vessel name      IMO  ...    Arr Port    Arr Date
59            Golden Strength  9413420  ...     Tianjin  2020-11-17
60                UHL Partner  9418999  ...  Vostochnyy  2020-11-23
61               Golden Pearl  9470375  ...  Caofeidian  2020-11-20
62  Boris Vilkitskiy (Tanker)  9000247  ...    Murmansk  2020-11-14
63               SCF Sakhalin  9307724  ...    Murmansk  2020-11-20

[5 rows x 15 columns]

In [75]:
df_2020.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 64 entries, 0 to 63
Data columns (total 15 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Vessel name       64 non-null     object
 1   IMO               64 non-null     int64
 2   Ice class         64 non-null     object
 3   Flag              64 non-null     object
 4   Owner / Operator  64 non-null     object
 5   Vessel type       64 non-null     object
 6   DWT               64 non-null     int64
 7   GRT               64 non-null     int64
 8   LOA               64 non-null     float64
 9   Dep Country       64 non-null     object
 10  Dep Port          64 non-null     object
 11  Dep Date          64 non-null     object
 12  Arr Country       64 non-null     object
 13  Arr Port          64 non-null     object
 14  Arr Date          64 non-null     object
dtypes: float64(1), int64(3), object(11)
memory usage: 7.6+ KB

In [76]:
df_2020.columns = ['vessel name','imo ship id','ice class','flag','ship operator','ship type','dead weight tonnage','grt','length overall','country of departure','port of departure','date of departure','country of arrival','port of arrival','date of arrival']
df_2020.head()

       vessel name  imo ship id  ...            port of arrival date of arrival
0          Barents      9278600  ...              Bolshoy Kamen      2020-08-07
1      S,Kuznetsov      9210359  ...  Petropavlovsk-Kamchatskiy      2020-08-06
2  Nordic Svalbard      9437323  ...                Vladivostok      2020-08-12
3          Tian En      9774587  ...                      Emden      2020-08-19
4           Samson      9114751  ...                 Bering Sea      2020-08-07

[5 rows x 15 columns]

In [77]:
df_2020 = basic_clean(df_2020)

New line characters have been removed. Detected 0 cell(s) with non-ASCII characters.
Null Count:
 vessel name             0
imo ship id             0
ice class               0
flag                    0
ship operator           0
ship type               0
dead weight tonnage     0
grt                     0
length overall          0
country of departure    0
port of departure       0
date of departure       0
country of arrival      0
port of arrival         0
date of arrival         0
dtype: int64

In [78]:
# 2021

df_2021 = data[2021]

df_2021.head()

      Vessel name      IMO Ice class  ... Arr Country     Arr Port    Arr Date
0         Tian En  9774587     Arc 4  ...       China      Qingdao  2021-08-17
1  Admiral Shmidt  9838838     Arc 5  ...      Canada      Nunavut  2021-08-11
2          Pugnax  9763849     Arc 7  ...       China       Yantai  2021-08-14
3  Golden Furious  9860128     Ice 2  ...      Russia     Murmansk  2021-08-06
4   Svyatoy Pavel  9035826     Arc 4  ...      Russia  Arkhangelsk  2021-08-03

[5 rows x 15 columns]

In [79]:
df_2021.tail()

     Vessel name      IMO Ice class  ... Arr Country       Arr Port    Arr Date
82    UHL Fusion  9785380     Arc 4  ...      Russia  Bolshoy Kamen  2021-11-29
83  Golden Pearl  9470375     Ice 2  ...       China         Rizhao  2021-12-02
84       Kumpula  9590802     Arc 4  ...      Norway         Narvik  2021-12-11
85     Sevmorput  8729810     Arc 5  ...      Russia       Nakhodka  2021-11-24
86        Pugnax  9763849     Arc 7  ...      Russia       Murmansk  2022-01-10

[5 rows x 15 columns]

In [80]:
df_2021.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 87 entries, 0 to 86
Data columns (total 15 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Vessel name       87 non-null     object
 1   IMO               87 non-null     int64
 2   Ice class         87 non-null     object
 3   Flag              87 non-null     object
 4   Owner / Operator  87 non-null     object
 5   Vessel type       87 non-null     object
 6   DWT               87 non-null     int64
 7   GRT               87 non-null     int64
 8   LOA               87 non-null     float64
 9   Dep Country       87 non-null     object
 10  Dep Port          87 non-null     object
 11  Dep Date          87 non-null     object
 12  Arr Country       87 non-null     object
 13  Arr Port          87 non-null     object
 14  Arr Date          87 non-null     object
dtypes: float64(1), int64(3), object(11)
memory usage: 10.3+ KB

In [81]:
df_2021.columns = ['vessel name','imo ship id','ice class','flag','ship operator','ship type','dead weight tonnage','grt','length overall','country of departure','port of departure','date of departure','country of arrival','port of arrival','date of arrival']
df_2021.head()

      vessel name  imo ship id  ... port of arrival date of arrival
0         Tian En      9774587  ...         Qingdao      2021-08-17
1  Admiral Shmidt      9838838  ...         Nunavut      2021-08-11
2          Pugnax      9763849  ...          Yantai      2021-08-14
3  Golden Furious      9860128  ...        Murmansk      2021-08-06
4   Svyatoy Pavel      9035826  ...     Arkhangelsk      2021-08-03

[5 rows x 15 columns]

In [82]:
df_2021 = basic_clean(df_2021)

New line characters have been removed. Detected 0 cell(s) with non-ASCII characters.
Null Count:
 vessel name             0
imo ship id             0
ice class               0
flag                    0
ship operator           0
ship type               0
dead weight tonnage     0
grt                     0
length overall          0
country of departure    0
port of departure       0
date of departure       0
country of arrival      0
port of arrival         0
date of arrival         0
dtype: int64

In [83]:
# 2022

df_2022 = data[2022]

df_2022.head()

    Vessel name      IMO  ...                   Arr Port    Arr Date
0         Audax  9763837  ...                   Murmansk  2022-02-17
1     Sevmorput  8729810  ...                   Murmansk  2022-02-23
2       Ruslana  9352339  ...                   Ust-Luga  2022-08-05
3  Svyatoy Petr  9035838  ...                Arkhangelsk  2022-07-30
4     Sevmorput  8729810  ...  Petropavlovsk-Kamchatskiy  2022-07-21

[5 rows x 15 columns]

In [84]:
df_2022.tail()

      Vessel name      IMO Ice class  ... Arr Country        Arr Port    Arr Date
38         PANDAR  9000235     Ice 2  ...      Russia     Arkhangelsk  2022-11-02
39       ELLADORA  8822375     Ice 1  ...      Russia     Vladivostok  2022-11-22
40  VASILY DINKOV  9372547     Arc 6  ...       China          Rizhao  2022-11-23
41    Monchegorsk  9404015     Arc 7  ...      Russia        Murmansk  2022-11-24
42      Sevmorput  8729810     Arc 5  ...      Russia  St, Petersburg  2022-12-15

[5 rows x 15 columns]

In [85]:
df_2022.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 43 entries, 0 to 42
Data columns (total 15 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Vessel name       43 non-null     object
 1   IMO               43 non-null     int64
 2   Ice class         43 non-null     object
 3   Flag              43 non-null     object
 4   Owner / Operator  43 non-null     object
 5   Vessel type       43 non-null     object
 6   DWT               43 non-null     int64
 7   GRT               43 non-null     int64
 8   LOA               43 non-null     int64
 9   Dep Country       43 non-null     object
 10  Dep Port          43 non-null     object
 11  Dep Date          43 non-null     object
 12  Arr Country       43 non-null     object
 13  Arr Port          43 non-null     object
 14  Arr Date          43 non-null     object
dtypes: int64(4), object(11)
memory usage: 5.2+ KB

In [86]:
df_2022.columns = ['vessel name','imo ship id','ice class','flag','ship operator','ship type','dead weight tonnage','grt','length overall','country of departure','port of departure','date of departure','country of arrival','port of arrival','date of arrival']
df_2022.head()

    vessel name  imo ship id  ...            port of arrival date of arrival
0         Audax      9763837  ...                   Murmansk      2022-02-17
1     Sevmorput      8729810  ...                   Murmansk      2022-02-23
2       Ruslana      9352339  ...                   Ust-Luga      2022-08-05
3  Svyatoy Petr      9035838  ...                Arkhangelsk      2022-07-30
4     Sevmorput      8729810  ...  Petropavlovsk-Kamchatskiy      2022-07-21

[5 rows x 15 columns]

In [87]:
df_2022 = basic_clean(df_2022)

New line characters have been removed. Detected 0 cell(s) with non-ASCII characters.
Null Count:
 vessel name             0
imo ship id             0
ice class               0
flag                    0
ship operator           0
ship type               0
dead weight tonnage     0
grt                     0
length overall          0
country of departure    0
port of departure       0
date of departure       0
country of arrival      0
port of arrival         0
date of arrival         0
dtype: int64

In [88]:
# 2023

df_2023 = data[2023]

df_2023.head()

   Vessel name      IMO Ice class  ...    Arr Date Cargo Approx tn     Cargo type
0       Pugnax  9763849     Arc 7  ...  2023-07-03        11748.80  general cargo
1    Sevmorput  8729810     Arc 5  ...  2023-07-21         4764.74     containers
2    Chukotka+  7927960     Arc 4  ...  2023-07-26            0.00        ballast
3  SCF Baltica  9305568     Arc 5  ...  2023-07-29            0.00        ballast
4       Pugnax  9763849     Arc 7  ...  2023-08-07            0.00        ballast

[5 rows x 17 columns]

In [89]:
df_2023.tail()

          Vessel name      IMO  ... Cargo Approx tn  Cargo type
74              Gingo  9182710  ...             0.0     ballast
75              Almaz  9150224  ...             0.0     ballast
76          NS Arctic  9413547  ...         99967.8   crude oil
77  Newnew Polar Bear  9313204  ...         13171.3  containers
78          Sevmorput  8729810  ...          2459.6  containers

[5 rows x 17 columns]

In [90]:
df_2023.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 79 entries, 0 to 78
Data columns (total 17 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Vessel name       79 non-null     object
 1   IMO               79 non-null     int64
 2   Ice class         79 non-null     object
 3   Flag              79 non-null     object
 4   Owner / Operator  79 non-null     object
 5   Vessel type       79 non-null     object
 6   DWT               79 non-null     int64
 7   GRT               79 non-null     int64
 8   LOA               79 non-null     int64
 9   Dep Country       79 non-null     object
 10  Dep Port          79 non-null     object
 11  Dep Date          79 non-null     object
 12  Arr Country       79 non-null     object
 13  Arr Port          79 non-null     object
 14  Arr Date          79 non-null     object
 15  Cargo Approx tn   79 non-null     float64
 16  Cargo type        79 non-null     object
dtypes: float64(1), int64(4), object(12)
memory usage: 10.6+ KB

In [92]:
df_2023.columns = ['vessel name','imo ship id','ice class','flag','ship operator','ship type','dead weight tonnage','grt','length overall','country of departure','port of departure','date of departure','country of arrival','port of arrival','date of arrival','approx cargo weight (tn)','cargo type']
df_2023.head()

   vessel name  imo ship id  ... approx cargo weight (tn)     cargo type
0       Pugnax      9763849  ...                 11748.80  general cargo
1    Sevmorput      8729810  ...                  4764.74     containers
2    Chukotka+      7927960  ...                     0.00        ballast
3  SCF Baltica      9305568  ...                     0.00        ballast
4       Pugnax      9763849  ...                     0.00        ballast

[5 rows x 17 columns]

In [93]:
df_2023 = basic_clean(df_2023)

New line characters have been removed. Detected 0 cell(s) with non-ASCII characters.
Null Count:
 vessel name                 0
imo ship id                 0
ice class                   0
flag                        0
ship operator               0
ship type                   0
dead weight tonnage         0
grt                         0
length overall              0
country of departure        0
port of departure           0
date of departure           0
country of arrival          0
port of arrival             0
date of arrival             0
approx cargo weight (tn)    0
cargo type                  0
dtype: int64

In [94]:
# 2024

df_2024 = data[2024]

df_2024.head()

   N          Ship_name      IMO  ...  NSR Entered  NSR   Left        Days at NSR
0  1              Audax  9763837  ...   21.01.2024         24.02.2024          34
1  1             Pugnax  9763849  ...   21.01.2024         24.02.2024          34
2  1  Shturman_Skuratov  9759915  ...   18.06.2024         29.06.2024          11
3  1   Korolev_Prospect  9826902  ...   25.07.2024         09.08.2024          15
4  1         Xue_Long_2  9829241  ...   17.07.2024         23.08.2024          37

[5 rows x 16 columns]