#### NSR Project Data Wrangling

In [1]:
# import necessary packages
import pandas as pd
import numpy as np
import os

In [2]:
# open csv files as pandas dataframes 

start_y = 2011
max_y = 2024
curr_y = start_y

path = '~/desktop/nsr-project/static/NSRData_CSV/'
data = {}

while curr_y <= max_y: 
    file_name = 'nsr_' + str(curr_y) + '.csv'
    df = pd.read_csv(os.path.join(path,file_name))
    data[curr_y] = df
    curr_y +=1

#### Clean up each dataframe

In [3]:
# Do dataset wide cleanup first?
# def functions to do some basic cleanup
def basic_clean(df):
    df = df.replace('\n',' ', regex=True)
    df = df.replace(['«','»'], ' ',regex=True)
    df = df.replace(',','.', regex=True)
    
    n=0
    for row_index, row in df.iterrows():
        for col_name, cell_val in row.items():
            if df[col_name].dtype == object:
                if not str(cell_val).isascii():
                    n+=1
                    print(col_name,row_index)
    print('New line characters have been removed. Detected', n, 'cell(s) with non-ASCII characters.\nNull Count:\n',df.isnull().sum())
    
    return df

##### Set up column standardization

In [4]:
# 2011

df_2011 = data[2011]
df_2011.head()

   Unnamed: 0    0  ...                     5                      6
0           0  NaN  ...       Port of Loading    Port of Destination
1           1  1.0  ...        Vitino, Russia         Ningbo,\nChina
2           2  2.0  ...        Vitino, Russia  Map Ta Phut, Thailand
3           3  3.0  ...        Vitino, Russia        Huizhou,\nChina
4           4  4.0  ...  Honningsvåg,\nNorway  Map Ta Phut, Thailand

[5 rows x 8 columns]

In [5]:
df_2011.tail()

    Unnamed: 0     0                1  ...        4            5            6
37          37  37.0        Ventspils  ...  ballast         East         West
38          38  38.0  Mikhail Kutuzov  ...  ballast         East         West
39          39  39.0      Ivan Kireev  ...  ballast  Archangelsk    Slavyanka
40          40  40.0          Vengeri  ...  ballast         West         East
41          41  41.0      Mar Adriana  ...  ballast    Rotterdam  Vladivostok

[5 rows x 8 columns]

In [6]:
df_2011.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 42 entries, 0 to 41
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  42 non-null     int64
 1   0           41 non-null     float64
 2   1           42 non-null     object
 3   2           42 non-null     object
 4   3           42 non-null     object
 5   4           42 non-null     object
 6   5           42 non-null     object
 7   6           42 non-null     object
dtypes: float64(1), int64(1), object(6)
memory usage: 2.8+ KB

In [7]:
# make row index 0 into column headers
df_2011.columns = df_2011.iloc[0]
df_2011 = df_2011[1:]
df_2011.reset_index(drop=True, inplace=True)
df_2011.rename(columns=str)

df_2011.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 41 entries, 0 to 40
Data columns (total 8 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   0                    41 non-null     int64
 1   nan                  41 non-null     float64
 2   Vessel’s Name        41 non-null     object
 3   Type                 41 non-null     object
 4   Flag                 41 non-null     object
 5   Cargo                41 non-null     object
 6   Port of Loading      41 non-null     object
 7   Port of Destination  41 non-null     object
dtypes: float64(1), int64(1), object(6)
memory usage: 2.7+ KB

In [8]:
# change column header names
df_2011.columns = ['index','index2','vessel name','type','flag','cargo','port of loading','port of destination']
df_2011.columns

Index(['index', 'index2', 'vessel name', 'type', 'flag', 'cargo',
       'port of loading', 'port of destination'],
      dtype='object')

In [9]:
df_2011 = df_2011.drop(['index','index2'],axis=1)

In [10]:
df_2011.head()

         vessel name  ...    port of destination
0       Perseverance  ...         Ningbo,\nChina
1       STI Heritage  ...  Map Ta Phut, Thailand
2            Marilee  ...        Huizhou,\nChina
3  Vladimir Tikhonov  ...  Map Ta Phut, Thailand
4     Stena Poseidon  ...  Incheon,\nSouth Korea

[5 rows x 6 columns]

In [11]:
df_2011 = basic_clean(df_2011)

port of loading 3
vessel name 29
New line characters have been removed. Detected 2 cell(s) with non-ASCII characters.
Null Count:
 vessel name            0
type                   0
flag                   0
cargo                  0
port of loading        0
port of destination    0
dtype: int64

In [12]:
df_2011.head()

         vessel name           type  ...      port of loading    port of destination
0       Perseverance  Tanker vessel  ...       Vitino. Russia          Ningbo. China
1       STI Heritage  Tanker vessel  ...       Vitino. Russia  Map Ta Phut. Thailand
2            Marilee  Tanker vessel  ...       Vitino. Russia         Huizhou. China
3  Vladimir Tikhonov  Tanker vessel  ...  Honningsvåg. Norway  Map Ta Phut. Thailand
4     Stena Poseidon  Tanker vessel  ...       Vitino. Russia   Incheon. South Korea

[5 rows x 6 columns]

In [13]:
# 2012
df_2012 = data[2012]

df_2012.head()

   Unnamed: 0  0  ...                     10   11
0           0  №  ...  Average speed,\nknots  NaN
1           1  1  ...                   5,8.  NaN
2           2  2  ...                    5,9  NaN
3           3  3  ...                    7,3  NaN
4           4  4  ...                    9,7  NaN

[5 rows x 13 columns]

In [14]:
df_2012.tail(10)

    Unnamed: 0  ...                             11
52          52  ...                            NaN
53          53  ...                            NaN
54          54  ...  Full\nDisplacement\nWestbound
55          55  ...                            NaN
56          56  ...                            NaN
57          57  ...                            NaN
58          58  ...                            NaN
59          59  ...                        472 075
60          60  ...                         63 986
61          61  ...                        536 061

[10 rows x 13 columns]

In [15]:
df_2012_totals = df_2012[54:62]
df_2012_totals.head(10)

    Unnamed: 0  ...                             11
54          54  ...  Full\nDisplacement\nWestbound
55          55  ...                            NaN
56          56  ...                            NaN
57          57  ...                            NaN
58          58  ...                            NaN
59          59  ...                        472 075
60          60  ...                         63 986
61          61  ...                        536 061

[8 rows x 13 columns]

In [16]:
df_2012 = df_2012[0:54]
df_2012.tail()

    Unnamed: 0   0                                 1  ...     9    10   11
49          49  42     Mv\n«Nordic\nOdyssey»\nPANAMA  ...  10.0  10.4  NaN
50          50  43       mv\n«Nordic\nOrion»\nPANAMA  ...  10.5  10,3  NaN
51          51  44  LNG\n«Ob River»\nMarshall Island  ...   9.0  12,5  NaN
52          52  45    icebreaker\n«Nordica»\nFINLAND  ...   NaN   NaN  NaN
53          53  46    icebreaker\n«Fennica»\nFINLAND  ...   NaN   NaN  NaN

[5 rows x 13 columns]

In [17]:
df_2012.head()

   Unnamed: 0  0  ...                     10   11
0           0  №  ...  Average speed,\nknots  NaN
1           1  1  ...                   5,8.  NaN
2           2  2  ...                    5,9  NaN
3           3  3  ...                    7,3  NaN
4           4  4  ...                    9,7  NaN

[5 rows x 13 columns]

In [18]:
# change column header names
# need to mold data into df.columns = ['index','index2','vessel name','type','flag','cargo','port of loading','port of destination']
df_2012.columns = ['index','index2', 'vessel and flag','ice class','ship operator','cargo','port of destination','port and date','entry to nsr','exit from nsr','time elapsed on nsr','avg speed','index3']
df_2012.columns

Index(['index', 'index2', 'vessel and flag', 'ice class', 'ship operator',
       'cargo', 'port of destination', 'port and date', 'entry to nsr',
       'exit from nsr', 'time elapsed on nsr', 'avg speed', 'index3'],
      dtype='object')

In [19]:
df_2012 = df_2012.drop(['index','index2','index3'],axis=1)
df_2012.columns

Index(['vessel and flag', 'ice class', 'ship operator', 'cargo',
       'port of destination', 'port and date', 'entry to nsr', 'exit from nsr',
       'time elapsed on nsr', 'avg speed'],
      dtype='object')

In [20]:
df_2012 = basic_clean(df_2012)
df_2012.head()

cargo 4
port of destination 4
port of destination 5
avg speed 8
avg speed 9
avg speed 13
cargo 30
port of destination 38
vessel and flag 41
entry to nsr 45
exit from nsr 45
ship operator 46
vessel and flag 48
port of destination 50
cargo 51
New line characters have been removed. Detected 15 cell(s) with non-ASCII characters.
Null Count:
 vessel and flag        0
ice class              2
ship operator          3
cargo                  1
port of destination    2
port and date          1
entry to nsr           2
exit from nsr          4
time elapsed on nsr    5
avg speed              5
dtype: int64

                  vessel and flag  ...             avg speed
0                 Vessel and Flag  ...  Average speed. knots
1             mt  Varzuga  Russia  ...                  5.8.
2              Mt  Indiga  Russia  ...                   5.9
3  Supply vessel  Vengeri  Russia  ...                   7.3
4      mt  Nordic Odyssey  PANAMA  ...                   9.7

[5 rows x 10 columns]

In [21]:
df_2012 = df_2012[1:]
df_2012.reset_index(inplace=True)
df_2012 = df_2012.drop('index',axis=1)
df_2012.head()

                  vessel and flag  ... avg speed
0             mt  Varzuga  Russia  ...      5.8.
1              Mt  Indiga  Russia  ...       5.9
2  Supply vessel  Vengeri  Russia  ...       7.3
3      mt  Nordic Odyssey  PANAMA  ...       9.7
4             mt  Marilee  NORWAY  ...       9.6

[5 rows x 10 columns]

In [22]:
# split some columns to sequester info nicer
# splitting vessel and flag --> vessel, flag
# splitting port and date --> starting port, trip start date

df_2012[['vessel', 'flag']] = df_2012['vessel and flag'].str.rsplit(n=1, expand=True)
df_2012.drop('vessel and flag',axis=1,inplace=True)

df_2012[['starting port','starting date']] = df_2012['port and date'].str.split(n=1,expand=True)
df_2012.drop('port and date',axis=1, inplace=True)

# df_2012[['cargo weight','cargo type']] = df_2012['cargo'].str.split('',n=1,regex=True)
# df_2012.drop('cargo',axis=1,inplace=True)

df_2012[['starting date','starting time']] = df_2012['starting date'].str.split(n=1,expand=True)

df_2012[['nsr entry date','nsr entry time']] = df_2012['entry to nsr'].str.split(n=1,expand=True)
df_2012.drop('entry to nsr',axis=1,inplace=True)

df_2012[['nsr exit date','nsr exit time']] = df_2012['exit from nsr'].str.split(n=1,expand=True)
df_2012.drop('exit from nsr',axis=1,inplace=True)

# need to get solve problem of time stamps 
df_2012.head()

              ice class         ship operator  ... nsr exit date nsr exit time
0                  Arc5              JSC MSCo  ...      16.07.12         10:00
1                  Arc5              JSC MSCo  ...      16.07.12         10:00
2  Ice 1A Super (Arc 5)             FEMCO LTD  ...      23.07.12         00:00
3         Ice 1A (Arc4)  Nordic Bulk Carriers  ...      23.07.12         05:00
4         Ice 1A (Arc4)             MARINVEST  ...      22.07.12         23:40

[5 rows x 15 columns]

In [23]:
# outlier cells need to conform

df_2012.loc[0,'time elapsed on nsr'] = 19.5
df_2012.loc[1,'time elapsed on nsr'] = 18.4

In [24]:
# deal with excess table headings that carried over from PDF version

df_2012.drop(9,axis=0,inplace=True)
df_2012.drop(10,axis=0,inplace=True)

df_2012.loc[8,'cargo'] = '60310 t. gas condensate NOVATEK'
df_2012.loc[8,'vessel'] = 'Mt Palva'
df_2012.loc[8,'flag'] = 'FINLAND'
df_2012.loc[8,'starting time'] = '19:30'

In [25]:
df_2012.drop(20,axis=0,inplace=True)
df_2012.drop(21,axis=0,inplace=True)

df_2012.loc[19,'vessel'] = 'supply vessel Tumcha (towing pipe-layer Nebula)'
df_2012.loc[19,'flag'] = 'Russia'
df_2012.loc[19,'starting port'] = 'Petropavlovsk-Kamchatskiy'
df_2012.loc[19,'starting date'] = '22.08.12'
df_2012.loc[19,'starting time'] = '14:10'

In [26]:
df_2012.drop(32,axis=0,inplace=True)
df_2012.drop(33,axis=0,inplace=True)

df_2012.loc[31,'cargo'] = '66275 t. Jet Fuel'
df_2012.loc[31,'port of destination'] = 'Porvoo, Finland'
df_2012.loc[31,'flag'] = 'Finland'
df_2012.loc[31,'vessel'] = 'mt Palva'
df_2012.loc[31,'starting port'] = 'Yosu, Republic of Korea'
df_2012.loc[31,'starting date'] = '05.09.12'
df_2012.loc[31,'nsr entry time'] = '10:35'
df_2012.loc[31,'nsr exit time'] = '21:30'

In [27]:
# drop last superfluous header

df_2012.drop(43,axis=0,inplace=True)

In [29]:
# fix rows that are out of standard
# clear theme stands out as limitation of pdfplumber and original PDFs: 
#     multiple types of data within a single cell creates problems

df_2012.loc[6,'starting port'] = 'Yosu, Republic of Korea'
df_2012.loc[6,'starting date'] = '30.06.12'
df_2012.loc[6,'starting time'] = '02:15'

df_2012.loc[11,'starting port'] = 'Port Vostchnyi'
df_2012.loc[11,'starting date'] = '28.07.12'
df_2012.loc[11,'starting time'] = np.nan

df_2012.loc[13,'starting port'] = 'Port of Nakhodka'
df_2012.loc[13,'starting date'] = '05.08.12'
df_2012.loc[13,'starting time'] = '14:30'

df_2012.loc[15,'starting port'] = 'Huanghua, China'
df_2012.loc[15,'starting date'] = '11.08.12'
df_2012.loc[15,'starting time'] = '11:00'

df_2012.loc[16,'starting port'] = 'Yosu, Republic of Korea'
df_2012.loc[16,'starting date'] = '11.08.12'
df_2012.loc[16,'starting time'] = '13:00'

df_2012.loc[17,'vessel'] = 'mt STI Harmony'
df_2012.loc[17,'flag'] = 'Marshall Islands'

df_2012.loc[29,'starting port'] = 'Huanghua, China'
df_2012.loc[29,'starting date'] = '06.09.12'
df_2012.loc[29,'starting time'] = '14:00'

df_2012.loc[36,'starting port'] = 'Baydaratskaya Bay'
df_2012.loc[36,'starting date'] = '19.09.12'
df_2012.loc[36,'starting time'] = '11:00'

df_2012.loc[38,'starting port'] = 'Baydaratskaya Bay'
df_2012.loc[38,'starting date'] = '01.10.12'
df_2012.loc[38,'starting time'] = '17:00'

df_2012.loc[40,'vessel'] = 'LNG Ob River'
df_2012.loc[40,'flag'] = 'Marshall Islands'
df_2012.loc[40,'starting port'] = 'Yosu, Republic of Korea'
df_2012.loc[40,'starting date'] = '30.09.12'
df_2012.loc[40,'starting time'] = '01:00'

df_2012.loc[46,'starting port'] = 'Qinhuangdao, China'
df_2012.loc[46,'starting date'] = np.nan
df_2012.loc[46,'starting time'] = np.nan

df_2012.loc[47,'vessel'] = 'Slavyanka Bay'
df_2012.loc[47,'flag'] = 'Russia'
df_2012.loc[47,'starting port'] = 'Petropavlovsk-Kamchatskiy'
df_2012.loc[47,'starting date'] = np.nan
df_2012.loc[47,'starting time'] = np.nan

df_2012.loc[48,'starting port'] = 'Vancouver, Canada'
df_2012.loc[48,'starting date'] = '26.10.12'
df_2012.loc[48,'starting time'] = '04:00'

df_2012.loc[49,'port of destination'] = 'Murmansk'
df_2012.loc[49,'starting port'] = 'Caofeidian, China'
df_2012.loc[49,'starting date'] = '28.10.12'
df_2012.loc[49,'starting time'] = '04:00'

df_2012.loc[50,'vessel'] = 'LNG Ob River'
df_2012.loc[50,'flag'] = 'Marshall Islands'
df_2012.loc[50,'starting port'] = 'Hammerfest, Norway'
df_2012.loc[50,'starting date'] = '07.11.12'
df_2012.loc[50,'starting time'] = '18:55'

df_2012.loc[51,'starting port'] = 'Alaska, USA'
df_2012.loc[51,'starting date'] = '12.11.12'
df_2012.loc[51,'starting time'] = '08:30'

df_2012.loc[52,'starting port'] = 'Alaska, USA'
df_2012.loc[52,'starting date'] = '12.11.12'
df_2012.loc[52,'starting time'] = '07:45'

df_2012

                    ice class  ...         nsr exit time
0                        Arc5  ...                 10:00
1                        Arc5  ...                 10:00
2        Ice 1A Super (Arc 5)  ...                 00:00
3               Ice 1A (Arc4)  ...                 05:00
4               Ice 1A (Arc4)  ...                 23:40
5               Ice-1A (Arc4)  ...                 15:20
6               Ice 1A (Arc4)  ...                 20:50
7                       Arc 5  ...                 15:00
8               Ice 1A (Arc4)  ...                 11:50
11                      Arc 5  ...                 02:00
12              Ice-1A (Arc4)  ...                 23:45
13                       Arc4  ...                 21:00
14              Ice 1A (Arc4)  ...                 15.37
15              Ice 1A (Arc4)  ...                 07:20
16              Ice 1A (Arc4)  ...                 00:30
17              Ice 1A (Arc4)  ...                 14:30
18              Ice 1A (Arc4)  ...                 14:05
19                       Arc4  ...  17:25 Yugorskiy Shar
22               1A BV (Arc4)  ...                 08:30
23              Ice 1A (Arc4)  ...                 22:30
24              Ice 1A (Arc4)  ...                 22:00
25              Ice 1A (Arc4)  ...                 18:30
26                       Arc4  ...               06:15 e
27              Icebreake r 6  ...                 22:00
28              Ice 1A (Arc4)  ...                 00:10
29              Ice-1A (Arc4)  ...                 04:45
30              Ice 1A (Arc4)  ...                 01:00
31                     Ice 1A  ...                 21:30
34                       Arc5  ...                 24:00
35                       Arc5  ...                 18:00
36                       Arc4  ...                 22:00
37              Ice 1A (Arc4)  ...                 01:00
38                      Arc 5  ...                 01:40
39              Ice 1A (Arc4)  ...                 08:40
40              Ice 1A (Arc4)  ...                 06:40
41              Ice-1A (Arc4)  ...                 07:25
42                       Arc5  ...                 08:00
44              Ice 1A (Arc4)  ...      18:42 м. Дежнёва
45              Icebreake r 6  ...                 16:00
46              Ice 1A (Arc4)  ...                 23:00
47                       Arc5  ...                 00:00
48              Ice 1A (Arc4)  ...                 04:00
49              Ice-1A (Arc4)  ...                 18:30
50              Ice 1A (Arc4)  ...    21:20 Dezhnev Cape
51  Polar-10 Icebreaker (DNV)  ...                   NaN
52  Polar-10 Icebreaker (DNV)  ...                   NaN

[46 rows x 15 columns]

In [ ]:
df_2012.info()

In [ ]:
pd.to_numeric(df_2012['time elapsed on nsr'])

In [ ]:
# 2013

df_2013 = data[2013]
df_2013.head()

In [ ]:
df_2013.tail(10)

In [ ]:
df_2013_totals = df_2013[77:85]
df_2013_totals.head(10)

In [ ]:
df_2013 = df_2013[:77]
df_2013.tail()

In [ ]:
df_2013.columns = ['index','index2','vessel and flag','ice class','grt (tons)','vessel operator','cargo','port of destination','port and date of departure','entry to nsr','exit from nsr','time elapsed on nsr','avg speed (knots)','index3','index4','index5']
df_2013.head()

In [ ]:
df_2013 = df_2013.drop(['index','index2','index3','index4','index5'],axis=1)
df_2013 = df_2013.drop([0],axis=0)
df_2013.head()

In [ ]:
df_2013 = basic_clean(df_2013)

In [ ]:
df_2013.head()

In [ ]:
# split columns into standardized column format

df_2013[['vessel','flag']] = df_2013['vessel and flag'].str.split('flag',n=1,expand=True)
df_2013.drop('vessel and flag', axis=1,inplace=True)

df_2013[['starting port','starting date','starting time']] = df_2013['port and date of departure'].str.split(n=2,expand=True)
df_2013.drop('port and date of departure',axis=1,inplace=True)

df_2013[['entry date','entry time','nsr entry location']] = df_2013['entry to nsr'].str.split(n=2,expand=True)
df_2013.drop('entry to nsr',axis=1,inplace=True)

df_2013[['exit date','exit time','nsr exit location']] = df_2013['exit from nsr'].str.split(n=2,expand=True)
df_2013.drop('exit from nsr',axis=1,inplace=True)

df_2013.head()

In [ ]:
# 2014

df_2014 = data[2014]
df_2014.head()

In [ ]:
df_2014.tail()

In [ ]:
# rename columns to get closer to standardization

df_2014.columns = ['index','index2','vessel','flag','cargo','GRT','nsr entry date','nsr entry location','nsr exit location','nsr exit date','time elapsed on nsr']
df_2014.head()

In [ ]:
# drop irrelevant columns and rows
df_2014.drop('index',axis=1,inplace=True)
df_2014.drop('index2',axis=1,inplace=True)
df_2014.drop(0,axis=0,inplace=True)
df_2014.drop(1,axis=0,inplace=True)

df_2014.reset_index(drop=True,inplace=True)

df_2014.head()

In [ ]:
df_2014 = basic_clean(df_2014)

In [ ]:
# 2015

df_2015 = data[2015]
df_2015.head()

In [ ]:
df_2015.info()

In [ ]:
df_2015.tail()

In [ ]:
# rename columns to closer adhere to standardization

df_2015.columns = ['index','index2','vessel','flag','ship operator','ice class','ship type','cargo type','cargo weight','max draught','port of departure','port of destination','icebreaker assistance','Kara Gate date and time','Cape Zhelaniya date and time','Cape Dezhnev date and time','time elapsed on nsr']
df_2015.head()

In [ ]:
# drop irrelevant columns and rows

df_2015.drop(19,axis=0,inplace=True)
df_2015.drop(0,axis=0,inplace=True)
df_2015.drop('index',axis=1,inplace=True)
df_2015.drop('index2',axis=1,inplace=True)

df_2015.head()

In [ ]:
df_2015 = basic_clean(df_2015)

In [ ]:
df_2015.head()

In [ ]:
# expand checkpoint fields separating date and time

df_2015[['Kara Gate date','Kara Gate time']] = df_2015['Kara Gate date and time'].str.split(n=1,expand=True)
df_2015.drop('Kara Gate date and time',axis=1,inplace=True)

df_2015[['Cape Zhelaniya date','Cape Zhelaniya time']] = df_2015['Cape Zhelaniya date and time'].str.split(n=1,expand=True)
df_2015.drop('Cape Zhelaniya date and time',axis=1,inplace=True)

df_2015[['Cape Dezhnev date','Cape Deshnev time']] = df_2015['Cape Dezhnev date and time'].str.split(n=1,expand=True)
df_2015.drop('Cape Dezhnev date and time',axis=1,inplace=True)

In [ ]:
df_2015.head()

In [ ]:
df_2015.tail()

In [ ]:
# 2016

df_2016 = data[2016]

df_2016.head()

In [ ]:
df_2016.tail()

In [ ]:
# standardize column names

df_2016.columns = ['index','index2','index3','vessel name','flag','ship operator','ice class','ship type','cargo type','cargo weight','dead weight tonnage','max draught','port of departure','port of destination','icebreaker assistance','Kara Gate date and time','Yugorskiy Strait date and time','Cape Zhelaniya date and time','Cape Dezhnev date and time','time elapsed on nsr']

df_2016.head()

In [ ]:
# drop unnecessary columns

df_2016.drop(['index','index2','index3'],axis=1,inplace=True)
df_2016.drop([0,19,20],axis=0,inplace=True)

df_2016.tail()

In [ ]:
df_2016 = basic_clean(df_2016)

In [ ]:
df_2016.head()

In [ ]:
# expand columns 

df_2016[['Kara Gate date','Kara Gate time']] = df_2016['Kara Gate date and time'].str.split(n=1,expand=True)

df_2016[['Yugorskiy Strait date','Yugorskiy Strait time']] = df_2016['Yugorskiy Strait date and time'].str.split(n=1,expand=True)

df_2016[['Cape Zhelaniya date','Cape Zhelaniya time']] = df_2016['Cape Zhelaniya date and time'].str.split(n=1,expand=True)

df_2016[['Cape Dezhnev date','Cape Dezhnev time']] = df_2016['Cape Dezhnev date and time'].str.split(n=1,expand=True)

df_2016.drop(['Kara Gate date and time','Yugorskiy Strait date and time','Cape Zhelaniya date and time','Cape Dezhnev date and time'],axis=1,inplace=True)

In [ ]:
df_2016.head()

In [ ]:
# 2017

df_2017 = data[2017]

df_2017.head()

In [ ]:
df_2017.tail()

In [ ]:
df_2017.columns = ['index','index2','vessel name','dead weight tonnage','grt','flag','ship operator','ship type','imo ship id','length overall','ice class','port of departure','departure date and time','nsr entrance point','nsr entry date','nsr exit point','nsr exit date','port of destination','arrival date','time elapsed on nsr']

df_2017.head()

In [ ]:
# drop unnecessary columns

df_2017.drop(['index','index2'],axis=1,inplace=True)

df_2017.drop(0,axis=0,inplace=True)

df_2017.head()

In [ ]:
df_2017 = basic_clean(df_2017)

In [ ]:
# expand columns
df_2017[['departure date','departure time']] = df_2017['departure date and time'].str.split(n=1,expand=True)
df_2017.drop('departure date and time',axis=1,inplace=True)

In [ ]:
df_2017.tail()

In [ ]:
# 2018

df_2018 = data[2018]
df_2018.head()

In [ ]:
df_2018.tail()

In [ ]:
df_2018.columns = ['index','index2','vessel name','ice class','flag','ship operator','ship type','grt','departure country','departure port','departure date','nsr entry point','nsr entry date','nsr exit point','nsr exit date','arrival country','arrival port','arrival date']
df_2018.head()

In [ ]:
df_2018.drop(['index','index2'],axis=1,inplace=True)
df_2018.drop([0,1],axis=0,inplace=True)
df_2018.reset_index(drop=True,inplace=True)
df_2018.head()

In [ ]:
df_2018 = basic_clean(df_2018)
df_2018.head()

In [ ]:
# 2019

df_2019 = data[2019]
df_2019.head()

In [ ]:
df_2019.info()

In [ ]:
df_2019.columns = ['vessel name','imo ship id','ice class','flag','ship operator','ship type','dead weight tonnage','grt','length overall','country of departure','port of departure','date of departure','country of arrival','port of arrival','date of arrival']

In [ ]:
df_2019.head()

In [ ]:
df_2019 = basic_clean(df_2019)

In [ ]:
# 2020

df_2020 = data[2020]

df_2020.head()

In [ ]:
df_2020.tail()

In [ ]:
df_2020.info()

In [ ]:
df_2020.columns = ['vessel name','imo ship id','ice class','flag','ship operator','ship type','dead weight tonnage','grt','length overall','country of departure','port of departure','date of departure','country of arrival','port of arrival','date of arrival']
df_2020.head()

In [ ]:
df_2020 = basic_clean(df_2020)

In [ ]:
# 2021

df_2021 = data[2021]

df_2021.head()

In [ ]:
df_2021.tail()

In [ ]:
df_2021.info()

In [ ]:
df_2021.columns = ['vessel name','imo ship id','ice class','flag','ship operator','ship type','dead weight tonnage','grt','length overall','country of departure','port of departure','date of departure','country of arrival','port of arrival','date of arrival']
df_2021.head()

In [ ]:
df_2021 = basic_clean(df_2021)

In [ ]:
# 2022

df_2022 = data[2022]

df_2022.head()

In [ ]:
df_2022.tail()

In [ ]:
df_2022.info()

In [ ]:
df_2022.columns = ['vessel name','imo ship id','ice class','flag','ship operator','ship type','dead weight tonnage','grt','length overall','country of departure','port of departure','date of departure','country of arrival','port of arrival','date of arrival']
df_2022.head()

In [ ]:
df_2022 = basic_clean(df_2022)

In [ ]:
# 2023

df_2023 = data[2023]

df_2023.head()

In [ ]:
df_2023.tail()

In [ ]:
df_2023.info()

In [ ]:
df_2023.columns = ['vessel name','imo ship id','ice class','flag','ship operator','ship type','dead weight tonnage','grt','length overall','country of departure','port of departure','date of departure','country of arrival','port of arrival','date of arrival','approx cargo weight (tn)','cargo type']
df_2023.head()

In [ ]:
df_2023 = basic_clean(df_2023)

In [ ]:
# 2024

df_2024 = data[2024]

df_2024.head()