#### NSR Project Data Wrangling

In [1]:
# import necessary packages
import pandas as pd
import numpy as np
import os

In [2]:
# open csv files as pandas dataframes 

start_y = 2011
max_y = 2018
curr_y = start_y

path = '~/desktop/nsr-project/NSRData_CSV/'
data = {}

while curr_y <= max_y: 
    file_name = 'nsr_' + str(curr_y) + '.csv'
    df = pd.read_csv(os.path.join(path,file_name))
    data[curr_y] = df
    curr_y +=1

#### Clean up each dataframe

In [3]:
# Do dataset wide cleanup first?

##### Set up column standardization

In [4]:
# 2011

df_2011 = data[2011]
df_2011.head()

   Unnamed: 0    0  ...                     5                      6
0           0  NaN  ...       Port of Loading    Port of Destination
1           1  1.0  ...        Vitino, Russia         Ningbo,\nChina
2           2  2.0  ...        Vitino, Russia  Map Ta Phut, Thailand
3           3  3.0  ...        Vitino, Russia        Huizhou,\nChina
4           4  4.0  ...  Honningsvåg,\nNorway  Map Ta Phut, Thailand

[5 rows x 8 columns]

In [5]:
df_2011.tail()

    Unnamed: 0     0                1  ...        4            5            6
37          37  37.0        Ventspils  ...  ballast         East         West
38          38  38.0  Mikhail Kutuzov  ...  ballast         East         West
39          39  39.0      Ivan Kireev  ...  ballast  Archangelsk    Slavyanka
40          40  40.0          Vengeri  ...  ballast         West         East
41          41  41.0      Mar Adriana  ...  ballast    Rotterdam  Vladivostok

[5 rows x 8 columns]

In [6]:
df_2011.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 42 entries, 0 to 41
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  42 non-null     int64
 1   0           41 non-null     float64
 2   1           42 non-null     object
 3   2           42 non-null     object
 4   3           42 non-null     object
 5   4           42 non-null     object
 6   5           42 non-null     object
 7   6           42 non-null     object
dtypes: float64(1), int64(1), object(6)
memory usage: 2.8+ KB

In [7]:
# make row index 0 into column headers
df_2011.columns = df_2011.iloc[0]
df_2011 = df_2011[1:]
df_2011.reset_index(drop=True, inplace=True)
df_2011.rename(columns=str)

df_2011.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 41 entries, 0 to 40
Data columns (total 8 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   0                    41 non-null     int64
 1   nan                  41 non-null     float64
 2   Vessel’s Name        41 non-null     object
 3   Type                 41 non-null     object
 4   Flag                 41 non-null     object
 5   Cargo                41 non-null     object
 6   Port of Loading      41 non-null     object
 7   Port of Destination  41 non-null     object
dtypes: float64(1), int64(1), object(6)
memory usage: 2.7+ KB

In [8]:
# change column header names
df_2011.columns = ['index','index2','vessel name','type','flag','cargo','port of loading','port of destination']
df_2011.columns

Index(['index', 'index2', 'vessel name', 'type', 'flag', 'cargo',
       'port of loading', 'port of destination'],
      dtype='object')

In [9]:
df_2011 = df_2011.drop(['index','index2'],axis=1)

In [10]:
df_2011.head()

         vessel name  ...    port of destination
0       Perseverance  ...         Ningbo,\nChina
1       STI Heritage  ...  Map Ta Phut, Thailand
2            Marilee  ...        Huizhou,\nChina
3  Vladimir Tikhonov  ...  Map Ta Phut, Thailand
4     Stena Poseidon  ...  Incheon,\nSouth Korea

[5 rows x 6 columns]

In [11]:
df_2011 = df_2011.replace('\n',' ',regex=True)

In [12]:
df_2011.head()

         vessel name           type  ...      port of loading    port of destination
0       Perseverance  Tanker vessel  ...       Vitino, Russia          Ningbo, China
1       STI Heritage  Tanker vessel  ...       Vitino, Russia  Map Ta Phut, Thailand
2            Marilee  Tanker vessel  ...       Vitino, Russia         Huizhou, China
3  Vladimir Tikhonov  Tanker vessel  ...  Honningsvåg, Norway  Map Ta Phut, Thailand
4     Stena Poseidon  Tanker vessel  ...       Vitino, Russia   Incheon, South Korea

[5 rows x 6 columns]

In [13]:
# 2012
df_2012 = data[2012]

df_2012.head()

   Unnamed: 0  0  ...                     10   11
0           0  №  ...  Average speed,\nknots  NaN
1           1  1  ...                   5,8.  NaN
2           2  2  ...                    5,9  NaN
3           3  3  ...                    7,3  NaN
4           4  4  ...                    9,7  NaN

[5 rows x 13 columns]

In [14]:
df_2012.tail(10)

    Unnamed: 0  ...                             11
52          52  ...                            NaN
53          53  ...                            NaN
54          54  ...  Full\nDisplacement\nWestbound
55          55  ...                            NaN
56          56  ...                            NaN
57          57  ...                            NaN
58          58  ...                            NaN
59          59  ...                        472 075
60          60  ...                         63 986
61          61  ...                        536 061

[10 rows x 13 columns]

In [15]:
df_2012_totals = df_2012[54:62]
df_2012_totals.head(10)

    Unnamed: 0  ...                             11
54          54  ...  Full\nDisplacement\nWestbound
55          55  ...                            NaN
56          56  ...                            NaN
57          57  ...                            NaN
58          58  ...                            NaN
59          59  ...                        472 075
60          60  ...                         63 986
61          61  ...                        536 061

[8 rows x 13 columns]

In [16]:
df_2012 = df_2012[0:54]
df_2012.tail()

    Unnamed: 0   0                                 1  ...     9    10   11
49          49  42     Mv\n«Nordic\nOdyssey»\nPANAMA  ...  10.0  10.4  NaN
50          50  43       mv\n«Nordic\nOrion»\nPANAMA  ...  10.5  10,3  NaN
51          51  44  LNG\n«Ob River»\nMarshall Island  ...   9.0  12,5  NaN
52          52  45    icebreaker\n«Nordica»\nFINLAND  ...   NaN   NaN  NaN
53          53  46    icebreaker\n«Fennica»\nFINLAND  ...   NaN   NaN  NaN

[5 rows x 13 columns]

In [17]:
df_2012.head()

   Unnamed: 0  0  ...                     10   11
0           0  №  ...  Average speed,\nknots  NaN
1           1  1  ...                   5,8.  NaN
2           2  2  ...                    5,9  NaN
3           3  3  ...                    7,3  NaN
4           4  4  ...                    9,7  NaN

[5 rows x 13 columns]

In [18]:
# change column header names
# need to mold data into df.columns = ['index','index2','vessel name','type','flag','cargo','port of loading','port of destination']
df_2012.columns = ['index','index2', 'vessel and flag','ice class','ship operator','cargo','port of destination','port and date','entry to nsr','exit from nsr','time elapsed on nsr','avg speed','index3']
df_2012.columns

Index(['index', 'index2', 'vessel and flag', 'ice class', 'ship operator',
       'cargo', 'port of destination', 'port and date', 'entry to nsr',
       'exit from nsr', 'time elapsed on nsr', 'avg speed', 'index3'],
      dtype='object')

In [19]:
df_2012 = df_2012.drop(['index','index2','index3'],axis=1)
df_2012.columns

Index(['vessel and flag', 'ice class', 'ship operator', 'cargo',
       'port of destination', 'port and date', 'entry to nsr', 'exit from nsr',
       'time elapsed on nsr', 'avg speed'],
      dtype='object')

In [22]:
df_2012.replace('\n',' ',regex=True,inplace=True)
df_2012.replace(['«','»'], ["'","'"], regex = False,inplace=True)
df_2012.head()

                  vessel and flag  ...             avg speed
0                 Vessel and Flag  ...  Average speed, knots
1             mt «Varzuga» Russia  ...                  5,8.
2              Mt «Indiga» Russia  ...                   5,9
3  Supply vessel «Vengeri» Russia  ...                   7,3
4      mt «Nordic Odyssey» PANAMA  ...                   9,7

[5 rows x 10 columns]

In [25]:
df_2012.drop(0,axis=0,inplace=True)
df_2012.reset_index()

    index  ...             avg speed
0       1  ...                  5,8.
1       2  ...                   5,9
2       3  ...                   7,3
3       4  ...                   9,7
4       5  ...                   9,6
5       6  ...                  10,0
6       7  ...                   9,4
7       8  ...               10,9 уз
8       9  ...               12,3 уз
9      10  ...  Average speed, knots
10     11  ...                   NaN
11     12  ...                     -
12     13  ...               12,3 уз
13     14  ...                  10,3
14     15  ...                  10,7
15     16  ...                   9,6
16     17  ...                  10,2
17     18  ...                  12,9
18     19  ...                  12,7
19     20  ...                     -
20     21  ...  Average speed, knots
21     22  ...                   NaN
22     23  ...                  13,3
23     24  ...                  12,4
24     25  ...                  10,7
25     26  ...                  10,3
26     27  ...                     -
27     28  ...                  10,4
28     29  ...                  13,2
29     30  ...                  12,6
30     31  ...                  13,5
31     32  ...                  11,8
32     33  ...  Average speed, knots
33     34  ...                   NaN
34     35  ...                   8,3
35     36  ...                   8,5
36     37  ...                   8,3
37     38  ...                  12,5
38     39  ...                   8,3
39     40  ...                  11,6
40     41  ...                  12,8
41     42  ...                  13,3
42     43  ...                   7,6
43     44  ...  Average speed, knots
44     45  ...                  12,8
45     46  ...                  12.8
46     47  ...                  13.3
47     48  ...                   8,5
48     49  ...                  10.4
49     50  ...                  10,3
50     51  ...                  12,5
51     52  ...                   NaN
52     53  ...                   NaN

[53 rows x 11 columns]