#### NSR Project Data Wrangling

In [1]:
# import necessary packages
import pandas as pd
import numpy as np
import os

In [2]:
# open csv files as pandas dataframes 

start_y = 2011
max_y = 2018
curr_y = start_y

path = '~/desktop/nsr-project/NSRData_CSV/'
data = {}

while curr_y <= max_y: 
    file_name = 'nsr_' + str(curr_y) + '.csv'
    df = pd.read_csv(os.path.join(path,file_name))
    data[curr_y] = df
    curr_y +=1

#### Clean up each dataframe

In [3]:
# Do dataset wide cleanup first?
# def functions to do some basic cleanup
def basic_clean(df):
    df = df.replace('\n',' ', regex=True)
    df = df.replace(['«','»'], ' ',regex=True)
    
    n=0
    for row_index, row in df.iterrows():
        for col_name, cell_val in row.items():
            if df[col_name].dtype == object:
                if not str(cell_val).isascii():
                    n+=1
                    print(col_name,row_index)
    print('New line characters have been removed. Detected', n, 'cells with non-ASCII characters.\n',df.isnull().sum())
    
    return df

##### Set up column standardization

In [4]:
# 2011

df_2011 = data[2011]
df_2011.head()

   Unnamed: 0    0  ...                     5                      6
0           0  NaN  ...       Port of Loading    Port of Destination
1           1  1.0  ...        Vitino, Russia         Ningbo,\nChina
2           2  2.0  ...        Vitino, Russia  Map Ta Phut, Thailand
3           3  3.0  ...        Vitino, Russia        Huizhou,\nChina
4           4  4.0  ...  Honningsvåg,\nNorway  Map Ta Phut, Thailand

[5 rows x 8 columns]

In [5]:
df_2011.tail()

    Unnamed: 0     0                1  ...        4            5            6
37          37  37.0        Ventspils  ...  ballast         East         West
38          38  38.0  Mikhail Kutuzov  ...  ballast         East         West
39          39  39.0      Ivan Kireev  ...  ballast  Archangelsk    Slavyanka
40          40  40.0          Vengeri  ...  ballast         West         East
41          41  41.0      Mar Adriana  ...  ballast    Rotterdam  Vladivostok

[5 rows x 8 columns]

In [6]:
df_2011.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 42 entries, 0 to 41
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  42 non-null     int64
 1   0           41 non-null     float64
 2   1           42 non-null     object
 3   2           42 non-null     object
 4   3           42 non-null     object
 5   4           42 non-null     object
 6   5           42 non-null     object
 7   6           42 non-null     object
dtypes: float64(1), int64(1), object(6)
memory usage: 2.8+ KB

In [7]:
# make row index 0 into column headers
df_2011.columns = df_2011.iloc[0]
df_2011 = df_2011[1:]
df_2011.reset_index(drop=True, inplace=True)
df_2011.rename(columns=str)

df_2011.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 41 entries, 0 to 40
Data columns (total 8 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   0                    41 non-null     int64
 1   nan                  41 non-null     float64
 2   Vessel’s Name        41 non-null     object
 3   Type                 41 non-null     object
 4   Flag                 41 non-null     object
 5   Cargo                41 non-null     object
 6   Port of Loading      41 non-null     object
 7   Port of Destination  41 non-null     object
dtypes: float64(1), int64(1), object(6)
memory usage: 2.7+ KB

In [8]:
# change column header names
df_2011.columns = ['index','index2','vessel name','type','flag','cargo','port of loading','port of destination']
df_2011.columns

Index(['index', 'index2', 'vessel name', 'type', 'flag', 'cargo',
       'port of loading', 'port of destination'],
      dtype='object')

In [9]:
df_2011 = df_2011.drop(['index','index2'],axis=1)

In [10]:
df_2011.head()

         vessel name  ...    port of destination
0       Perseverance  ...         Ningbo,\nChina
1       STI Heritage  ...  Map Ta Phut, Thailand
2            Marilee  ...        Huizhou,\nChina
3  Vladimir Tikhonov  ...  Map Ta Phut, Thailand
4     Stena Poseidon  ...  Incheon,\nSouth Korea

[5 rows x 6 columns]

In [11]:
df_2011 = basic_clean(df_2011)

port of loading 3
vessel name 29
New line characters have been removed. Detected 2 cells with non-ASCII characters.
 vessel name            0
type                   0
flag                   0
cargo                  0
port of loading        0
port of destination    0
dtype: int64

In [12]:
df_2011.head()

         vessel name           type  ...      port of loading    port of destination
0       Perseverance  Tanker vessel  ...       Vitino, Russia          Ningbo, China
1       STI Heritage  Tanker vessel  ...       Vitino, Russia  Map Ta Phut, Thailand
2            Marilee  Tanker vessel  ...       Vitino, Russia         Huizhou, China
3  Vladimir Tikhonov  Tanker vessel  ...  Honningsvåg, Norway  Map Ta Phut, Thailand
4     Stena Poseidon  Tanker vessel  ...       Vitino, Russia   Incheon, South Korea

[5 rows x 6 columns]

In [13]:
# 2012
df_2012 = data[2012]

df_2012.head()

   Unnamed: 0  0  ...                     10   11
0           0  №  ...  Average speed,\nknots  NaN
1           1  1  ...                   5,8.  NaN
2           2  2  ...                    5,9  NaN
3           3  3  ...                    7,3  NaN
4           4  4  ...                    9,7  NaN

[5 rows x 13 columns]

In [14]:
df_2012.tail(10)

    Unnamed: 0  ...                             11
52          52  ...                            NaN
53          53  ...                            NaN
54          54  ...  Full\nDisplacement\nWestbound
55          55  ...                            NaN
56          56  ...                            NaN
57          57  ...                            NaN
58          58  ...                            NaN
59          59  ...                        472 075
60          60  ...                         63 986
61          61  ...                        536 061

[10 rows x 13 columns]

In [15]:
df_2012_totals = df_2012[54:62]
df_2012_totals.head(10)

    Unnamed: 0  ...                             11
54          54  ...  Full\nDisplacement\nWestbound
55          55  ...                            NaN
56          56  ...                            NaN
57          57  ...                            NaN
58          58  ...                            NaN
59          59  ...                        472 075
60          60  ...                         63 986
61          61  ...                        536 061

[8 rows x 13 columns]

In [16]:
df_2012 = df_2012[0:54]
df_2012.tail()

    Unnamed: 0   0                                 1  ...     9    10   11
49          49  42     Mv\n«Nordic\nOdyssey»\nPANAMA  ...  10.0  10.4  NaN
50          50  43       mv\n«Nordic\nOrion»\nPANAMA  ...  10.5  10,3  NaN
51          51  44  LNG\n«Ob River»\nMarshall Island  ...   9.0  12,5  NaN
52          52  45    icebreaker\n«Nordica»\nFINLAND  ...   NaN   NaN  NaN
53          53  46    icebreaker\n«Fennica»\nFINLAND  ...   NaN   NaN  NaN

[5 rows x 13 columns]

In [17]:
df_2012.head()

   Unnamed: 0  0  ...                     10   11
0           0  №  ...  Average speed,\nknots  NaN
1           1  1  ...                   5,8.  NaN
2           2  2  ...                    5,9  NaN
3           3  3  ...                    7,3  NaN
4           4  4  ...                    9,7  NaN

[5 rows x 13 columns]

In [18]:
# change column header names
# need to mold data into df.columns = ['index','index2','vessel name','type','flag','cargo','port of loading','port of destination']
df_2012.columns = ['index','index2', 'vessel and flag','ice class','ship operator','cargo','port of destination','port and date','entry to nsr','exit from nsr','time elapsed on nsr','avg speed','index3']
df_2012.columns

Index(['index', 'index2', 'vessel and flag', 'ice class', 'ship operator',
       'cargo', 'port of destination', 'port and date', 'entry to nsr',
       'exit from nsr', 'time elapsed on nsr', 'avg speed', 'index3'],
      dtype='object')

In [19]:
df_2012 = df_2012.drop(['index','index2','index3'],axis=1)
df_2012.columns

Index(['vessel and flag', 'ice class', 'ship operator', 'cargo',
       'port of destination', 'port and date', 'entry to nsr', 'exit from nsr',
       'time elapsed on nsr', 'avg speed'],
      dtype='object')

In [20]:
df_2012 = basic_clean(df_2012)
df_2012.head()

cargo 4
port of destination 4
port of destination 5
avg speed 8
avg speed 9
avg speed 13
cargo 30
port of destination 38
vessel and flag 41
entry to nsr 45
exit from nsr 45
ship operator 46
vessel and flag 48
port of destination 50
cargo 51
New line characters have been removed. Detected 15 cells with non-ASCII characters.
 vessel and flag        0
ice class              2
ship operator          3
cargo                  1
port of destination    2
port and date          1
entry to nsr           2
exit from nsr          4
time elapsed on nsr    5
avg speed              5
dtype: int64

                  vessel and flag  ...             avg speed
0                 Vessel and Flag  ...  Average speed, knots
1             mt  Varzuga  Russia  ...                  5,8.
2              Mt  Indiga  Russia  ...                   5,9
3  Supply vessel  Vengeri  Russia  ...                   7,3
4      mt  Nordic Odyssey  PANAMA  ...                   9,7

[5 rows x 10 columns]

In [21]:
df_2012 = df_2012[1:]
df_2012.reset_index(inplace=True)
df_2012 = df_2012.drop('index',axis=1)
df_2012.head()

                  vessel and flag  ... avg speed
0             mt  Varzuga  Russia  ...      5,8.
1              Mt  Indiga  Russia  ...       5,9
2  Supply vessel  Vengeri  Russia  ...       7,3
3      mt  Nordic Odyssey  PANAMA  ...       9,7
4             mt  Marilee  NORWAY  ...       9,6

[5 rows x 10 columns]

In [22]:
# split some columns to sequester info nicer
# splitting vessel and flag --> vessel, flag
# splitting port and date --> starting port, trip start date
df_2012[['vessel', 'flag']] = df_2012['vessel and flag'].str.rsplit(n=1, expand=True)
df_2012.drop('vessel and flag',axis=1,inplace=True)

df_2012[['starting port','starting date']] = df_2012['port and date'].str.split(n=1,expand=True)
df_2012.drop('port and date',axis=1, inplace=True)

# df_2012[['cargo weight','cargo type']] = df_2012['cargo'].str.split('',n=1,regex=True)
# df_2012.drop('cargo',axis=1,inplace=True)

df_2012[['starting date','starting time']] = df_2012['starting date'].str.split(n=1,expand=True)

df_2012[['nsr entry date','nsr entry time']] = df_2012['entry to nsr'].str.split(n=1,expand=True)
df_2012.drop('entry to nsr',axis=1,inplace=True)

df_2012[['nsr exit date','nsr exit time']] = df_2012['exit from nsr'].str.split(n=1,expand=True)
df_2012.drop('exit from nsr',axis=1,inplace=True)

# need to get solve problem of time stamps 
df_2012.head()

              ice class         ship operator  ... nsr exit date nsr exit time
0                  Arc5              JSC MSCo  ...      16.07.12         10:00
1                  Arc5              JSC MSCo  ...      16.07.12         10:00
2  Ice 1A Super (Arc 5)             FEMCO LTD  ...      23.07.12         00:00
3         Ice 1A (Arc4)  Nordic Bulk Carriers  ...      23.07.12         05:00
4         Ice 1A (Arc4)             MARINVEST  ...      22.07.12         23:40

[5 rows x 15 columns]

In [23]:
# standardize cell structure and ensure ASCII characters
df_2012.loc[0,'time elapsed on nsr'] = 19.5
df_2012.loc[1,'time elapsed on nsr'] = 17.4

df_2012.head()

              ice class         ship operator  ... nsr exit date nsr exit time
0                  Arc5              JSC MSCo  ...      16.07.12         10:00
1                  Arc5              JSC MSCo  ...      16.07.12         10:00
2  Ice 1A Super (Arc 5)             FEMCO LTD  ...      23.07.12         00:00
3         Ice 1A (Arc4)  Nordic Bulk Carriers  ...      23.07.12         05:00
4         Ice 1A (Arc4)             MARINVEST  ...      22.07.12         23:40

[5 rows x 15 columns]

In [24]:
# 2013

df_2013 = data[2013]
df_2013.head()

   Unnamed: 0    0                                    1  ...   12   13   14
0           0  No.                      Vessel and Flag  ...  NaN  NaN  NaN
1           1    1           mt\n«Varzuga»\nflag RUSSIA  ...  NaN  NaN  NaN
2           2    2            mt\n«Indiga»\nflag RUSSIA  ...  NaN  NaN  NaN
3           3    3      mv\n«Nordic Orion»\nflag PANAMA  ...  NaN  NaN  NaN
4           4    4  mv\n«Boris Vilkitskiy»\nflag RUSSIA  ...  NaN  NaN  NaN

[5 rows x 16 columns]

In [25]:
df_2013.tail(10)

    Unnamed: 0               0  ...                  13                  14
75          75              67  ...                 NaN                 NaN
76          76              68  ...                 NaN                 NaN
77          77  Type of\ncargo  ...  Empty\nvessels\nWB  WB\ndispl.,\ntones
78          78          Liquid  ...                 NaN                 NaN
79          79            Bulk  ...                 NaN                 NaN
80          80             LNG  ...                 NaN                 NaN
81          81   General cargo  ...                 NaN                 NaN
82          82      Ballasting  ...                  14             467 445
83          83      Reposition  ...                   3              29 388
84          84          TOTAL:  ...                  17             496 833

[10 rows x 16 columns]

In [26]:
df_2013_totals = df_2013[77:85]
df_2013_totals.head(10)

    Unnamed: 0               0  ...                  13                  14
77          77  Type of\ncargo  ...  Empty\nvessels\nWB  WB\ndispl.,\ntones
78          78          Liquid  ...                 NaN                 NaN
79          79            Bulk  ...                 NaN                 NaN
80          80             LNG  ...                 NaN                 NaN
81          81   General cargo  ...                 NaN                 NaN
82          82      Ballasting  ...                  14             467 445
83          83      Reposition  ...                   3              29 388
84          84          TOTAL:  ...                  17             496 833

[8 rows x 16 columns]

In [27]:
df_2013 = df_2013[:77]
df_2013.tail()

    Unnamed: 0   0                                          1  ...   12   13   14
72          72  64          mv «HHL Hong\nKong»\nflag LIBERIA  ...  NaN  NaN  NaN
73          73  65        icebreaker\n«Fennica»\nflag FINLAND  ...  NaN  NaN  NaN
74          74  66                  mt\n«Indiga»\nflag RUSSIA  ...  NaN  NaN  NaN
75          75  67  mv «HHL Lagos»\nflag Antigua and\nBarbuda  ...  NaN  NaN  NaN
76          76  68                     mv «Yuri\nArshenevsky»  ...  NaN  NaN  NaN

[5 rows x 16 columns]

In [28]:
df_2013.columns = ['index','index2','vessel and flag','ice class','grt (tons)','vessel operator','cargo','port of destination','port and date of departure','entry to nsr','exit from nsr','time elapsed on nsr','avg speed (knots)','index3','index4','index5']
df_2013.head()

   index index2                      vessel and flag  ... index3 index4 index5
0      0    No.                      Vessel and Flag  ...    NaN    NaN    NaN
1      1      1           mt\n«Varzuga»\nflag RUSSIA  ...    NaN    NaN    NaN
2      2      2            mt\n«Indiga»\nflag RUSSIA  ...    NaN    NaN    NaN
3      3      3      mv\n«Nordic Orion»\nflag PANAMA  ...    NaN    NaN    NaN
4      4      4  mv\n«Boris Vilkitskiy»\nflag RUSSIA  ...    NaN    NaN    NaN

[5 rows x 16 columns]

In [29]:
df_2013 = df_2013.drop(['index','index2','index3','index4','index5'],axis=1)
df_2013 = df_2013.drop([0],axis=0)
df_2013.head()

                       vessel and flag  ... avg speed (knots)
1           mt\n«Varzuga»\nflag RUSSIA  ...               7,0
2            mt\n«Indiga»\nflag RUSSIA  ...               9,2
3      mv\n«Nordic Orion»\nflag PANAMA  ...               5,4
4  mv\n«Boris Vilkitskiy»\nflag RUSSIA  ...               4,3
5            mt\n«Indiga»\nflag RUSSIA  ...               7,2

[5 rows x 11 columns]

In [30]:
df_2013 = basic_clean(df_2013)

port of destination 1
vessel and flag 10
cargo 34
port and date of departure 75
New line characters have been removed. Detected 4 cells with non-ASCII characters.
 vessel and flag               1
ice class                     2
grt (tons)                    3
vessel operator               2
cargo                         1
port of destination           1
port and date of departure    1
entry to nsr                  1
exit from nsr                 1
time elapsed on nsr           3
avg speed (knots)             3
dtype: int64

In [31]:
df_2013.head()

                     vessel and flag  ... avg speed (knots)
1           mt  Varzuga  flag RUSSIA  ...               7,0
2            mt  Indiga  flag RUSSIA  ...               9,2
3      mv  Nordic Orion  flag PANAMA  ...               5,4
4  mv  Boris Vilkitskiy  flag RUSSIA  ...               4,3
5            mt  Indiga  flag RUSSIA  ...               7,2

[5 rows x 11 columns]

In [32]:
# split columns into standardized column format

df_2013[['vessel','flag']] = df_2013['vessel and flag'].str.split('flag',n=1,expand=True)
df_2013.drop('vessel and flag', axis=1,inplace=True)

df_2013[['starting port','starting date','starting time']] = df_2013['port and date of departure'].str.split(n=2,expand=True)
df_2013.drop('port and date of departure',axis=1,inplace=True)

df_2013[['entry date','entry time','nsr entry location']] = df_2013['entry to nsr'].str.split(n=2,expand=True)
df_2013.drop('entry to nsr',axis=1,inplace=True)

df_2013[['exit date','exit time','nsr exit location']] = df_2013['exit from nsr'].str.split(n=2,expand=True)
df_2013.drop('exit from nsr',axis=1,inplace=True)

df_2013.head()

       ice class grt (tons)  ... exit time nsr exit location
1           Arc5     11 290  ...     14:00        c. Dezhnev
2           Arc5     11 290  ...     09:20             Pevek
3  Ice-1A (Arc4)     40 142  ...     08:55        c. Dezhnev
4           Arc4      5 025  ...     24:00      Khatanga Bay
5           Arc5     11 290  ...     12:50            Ob Bay

[5 rows x 18 columns]

In [33]:
# 2014

df_2014 = data[2014]
df_2014.head()

   Unnamed: 0  ...                   9
0           0  ...  Days spent\nat NSR
1           1  ...                 NaN
2           2  ...                  30
3           3  ...                  13
4           4  ...                  43

[5 rows x 11 columns]

In [34]:
df_2014.tail()

    Unnamed: 0   0            1  ...            7         8   9
51          51  18      Varzuga  ...   port Pevek  28.10.14  11
52          52  19       Indiga  ...  c. Zhelania  17.11.14  28
53          53  20      Varzuga  ...  c. Zhelania  17.11.14  17
54          54  21       Indiga  ...  c. Zhelania  17.11.14  13
55          55  22  Ivan Ryabov  ...  c. Zhelania  16.11.14  10

[5 rows x 11 columns]

In [35]:
# rename columns to get closer to standardization

df_2014.columns = ['index','index2','vessel','flag','cargo','GRT','nsr entry date','nsr entry location','nsr exit location','nsr exit date','time elapsed on nsr']
df_2014.head()

   index  ... time elapsed on nsr
0      0  ...  Days spent\nat NSR
1      1  ...                 NaN
2      2  ...                  30
3      3  ...                  13
4      4  ...                  43

[5 rows x 11 columns]

In [36]:
# drop irrelevant columns and rows
df_2014.drop('index',axis=1,inplace=True)
df_2014.drop('index2',axis=1,inplace=True)
df_2014.drop(0,axis=0,inplace=True)
df_2014.drop(1,axis=0,inplace=True)

df_2014.reset_index(drop=True,inplace=True)

df_2014.head()

               vessel    flag  ... nsr exit date time elapsed on nsr
0  Kapitan Khlebnikov  Russia  ...      28.07.14                  30
1          Tor Viking  Sweden  ...      16.07.14                  13
2     Anichkov Bridge  Russia  ...      17.08.14                  43
3                Oden  Sweden  ...      17.08.14                  39
4     Yaroslav Mydryy  Russia  ...      28.07.14                  19

[5 rows x 9 columns]

In [37]:
df_2014 = basic_clean(df_2014)

New line characters have been removed. Detected 0 cells with non-ASCII characters.
 vessel                 1
flag                   1
cargo                  1
GRT                    1
nsr entry date         1
nsr entry location     1
nsr exit location      1
nsr exit date          1
time elapsed on nsr    1
dtype: int64

In [38]:
# 2015

df_2015 = data[2015]
df_2015.head()

   Unnamed: 0  0  ...                     14                         15
0           0  №  ...  EBNSR\n(Cape Dezhnev)  NSR\npassage\ntime (days)
1           1  1  ...         15.08.15 23:30                       16,9
2           2  2  ...          02.08.15 3:30                        8,5
3           3  3  ...          16.08.15 8:23                        9,7
4           4  4  ...         14.08.15 12:23                       10,3

[5 rows x 17 columns]

In [39]:
df_2015.tail()

    Unnamed: 0      0             1  ...              13             14    15
15          15     15  Volk Arktiki  ...             NaN  14.10.15 2:30  14,3
16          16     16      Palladiy  ...             NaN  25.10.15 2:00  16,3
17          17     17      Kigoriak  ...             NaN  08.11.15 6:20  13,9
18          18     18    Tor Viking  ...  10.12.15 12:00  29.11.15 7:10  11,2
19          19  Total           NaN  ...             NaN            NaN  10,6

[5 rows x 17 columns]

In [40]:
# rename columns to closer adhere to standardization

df_2015.columns = ['index','index2','vessel','flag','ship operator','ice class','ship type','cargo type','cargo weight','max draught','port of departure','port of destination','icebreaker assistance','Kara Gate date and time','Cape Zhelaniya date and time','Cape Dezhnev date and time','time elapsed on nsr']
df_2015.head()

   index index2  ... Cape Dezhnev date and time        time elapsed on nsr
0      0      №  ...      EBNSR\n(Cape Dezhnev)  NSR\npassage\ntime (days)
1      1      1  ...             15.08.15 23:30                       16,9
2      2      2  ...              02.08.15 3:30                        8,5
3      3      3  ...              16.08.15 8:23                        9,7
4      4      4  ...             14.08.15 12:23                       10,3

[5 rows x 17 columns]

In [41]:
# drop irrelevant columns and rows

df_2015.drop(19,axis=0,inplace=True)
df_2015.drop(0,axis=0,inplace=True)
df_2015.drop('index',axis=1,inplace=True)
df_2015.drop('index2',axis=1,inplace=True)

df_2015.head()

                                      vessel  ... time elapsed on nsr
1  Yasnyi (with\nfloating crane СПК-\n42150)  ...                16,9
2                                 Yong Sheng  ...                 8,5
3                                 Winter Bay  ...                 9,7
4                                   Garmonia  ...                10,3
5                                  Happy Sky  ...                 7,7

[5 rows x 15 columns]